### ISSUE TITLE
Add support for hooks in MySQL integration

### ISSUE THREAD

**Issue by rubencallewaert** [DataDog/dd-trace-js#1033]
I would like to be able to add the parameters of a MySQL query to it's span.
Right now there is no documented way for doing so.

Perhaps we can add support for hooks to the MySQL integration?

**Comment by rochdev** [comment]
This could be implemented in 2 ways with different pros/cons:

1) Adding a configuration option to automatically capture the query parameters as tags. The main advantage of this approach is that it would be the easiest one to implement and the simplest one to use.

2) Adding span hooks for the `mysql` plugin. This approach would be a lot more flexible and would allow updating anything on the span, but would be more difficult to use and it's unclear which objects should be passed to the hook (other than the span).

Is this the only information you need to add to the span? If that's the case then implementing the configuration option will definitely be faster.

In any case, since right now this is not implemented yet, I can provide a workaround to alter the `mysql.query` span after the query has completed. Basically, every time a span is finished, it's added to the trace on its internal span context. While this is private property that should not generally be accessed, you could use this to add the query parameters until the feature is implemented.

For example:

```js
connection.query('SELECT * FROM `table` WHERE `name` = ?', ['page'], (err, results, fields) => {
  // the mysql span has finished just before this callback is run, so it will be last in the trace
  const finished = tracer.scope().active().context()._trace.finished
  const span = finished[finished.length - 1]

  span.setTag('mysql.query.params.name', 'page')
});
```

**Comment by rubencallewaert** [comment]
I don't think there's anything else I would want to add to the span of a MySQL query. So the configuration option would indeed work just fine.

Thanks for the workaround!

**Comment by tlhunter** [comment]
Looks like this was solved but we forgot to close it. Feel free to reopen if I'm wrong!
