### ISSUE TITLE
Connecting to data-dog agent should be optional

### ISSUE THREAD

**Issue by Harry-027** [DataDog/dd-trace-js#1075]
**Issue :** I'm using dd-trace-js to inject trace & span Ids in application logs. My app is hosted on ECS docker container. I'm using aws logdriver which directly write logs to CloudWatch & I'm able to aggregate those logs from Cloudwatch using direct datadog aws integration. Therefore I need not to send any metrics to datadog agent. But on invoking tracer.init(), it tries to connect to datadog agent automatically and throws socket hung up error in its absence on host machine . Connecting to datadog agent should be an optional feature.

**Comment by rochdev** [comment]
If you are not using the tracer, then you also shouldn't inject the trace and span IDs to your logs since they will be useless as they won't be referencing anything since the traces were not sent. You would need to either install the agent so that the traces are sent and the IDs will then properly correlate your logs with your traces, or remove the tracer completely if you do not need tracing.

**Comment by rochdev** [comment]
Closing this since the agent is required for tracing which is the purpose of the library. Please reopen if you still need more clarification.
