### ISSUE TITLE
Tracing user id in microservices best practice?

### ISSUE THREAD

**Issue by kaievns** [DataDog/dd-trace-js#1091]
Ohi there, I was wondering if someone could help me to wrap my head around this problem I have?

So, I want to tag a distributed trace with a user ID in a microservices environment. So that if a user is having a problem, the engineers could dive into the data, and filter by a tag `user-id: 123` and get the history of the user's requests throughout the system.

I found the `Span#addTag` that's kinda handy. but it doesnt quite work the way i want it. consider  the following app:

```js
const app = express();

app.use(async function auth() {
  const user = await fetchUser();
  const currentSpan = tracer.scope().active();

  currentSpan.setTag('user-id', user.id);
});

app.get('/thing', async (req, res) => {
  const stuff = await axios.get('http://another-service/stuff');
  res.jso(stuff);
});
```

now if i fire up this app and hit the `/thing` ill get a stack trace, where only the auth middleware span is tagged with the user id

```
[             GET /thing                                                     ]
  [  auth tag: user-id: 123 ]  [   the thing handler    ]
                                                [ GET /stuff ]
```

what i would like to happen is that the parent `GET /thing` get tagged so it would be searcheable, but also the child trace `GET /stuff` get tagged as well and the user-id tag get propagated automatically through all the nested calls that services as well.

i can imagine that this is a common case scenario. im just failing to find some best practice information about this, and i dont want to reinvent the wheel. so if someone could shed some light how this sort of thing is normally handled with dd-trace, i would love you to the end

thanks for reading this far :)

**Comment by rochdev** [comment]
Generally speaking, you would search for traces for this user ID, and that would give you all the root spans that were tagged. Then you would find the other spans from all other connected services from that span.

If you want the user ID to actually be on the individual spans, you would have to do it manually using baggage items like this:

```js
// service A
span.setTag('user.id', 123)
span.setBattageItem('user_id', 123)

// service B
span.setTag('user.id', span.getBaggageItem('user_id'))
```

Once a baggage item is set, it propagates to all future spans in the trace so that it can be recovered in the other services. Setting baggage items as tags must be done manually though. If you think there should be a configuration to do this automatically I'm definitely open to the idea, but I would recommend reaching out to support first as they may be able to help you with your use case using the existing functionalities.

**Comment by MadRabbit** [comment]
hey, thank you for sharing this, i was looking at the baggage items and wasnt sure if that's the way to go, so, thank you for confirming.

could you also confirm that i got this right about the search. the root spans should turn up in the search when their children got tagged, is that correct?

because i dont think it quite works for me, like in the example above, when i add the user-id tag, the auth middleware span get tagged, and i can see it in APM, but when i search by that tag nothing turns up in the search results

**Comment by MadRabbit** [comment]
for example here i can see the `user_id` tag in the auth middleware
![image](https://user-images.githubusercontent.com/14523/93830274-1cc15800-fcb3-11ea-8b54-4b636ab89a7a.png)

and when i search for it nothing turns up
![image](https://user-images.githubusercontent.com/14523/93830314-382c6300-fcb3-11ea-8036-87e02825ec86.png)

i tried to remove all other tags as well, that didnt help

**Comment by MadRabbit** [comment]
is there a way for me to tag the root span somehow in the request?

**Comment by rochdev** [comment]
The root span will only show up if it was tagged explicitly. Otherwise you would find the children depending on your filters, and then clicking on a child would show you the entire trace including the root.

If you want to tag the root span of the request explicitly, you would have to store the information on the `Request` object and then add it to the request span with a span hook on the plugin:

```js
// hook will run before every request ends
tracer.use('express', {
  hooks: {
    request: (span, req, res) => {
      span.setTag('user-id', req.userId)
    }
  }
})

app.use((req, res, next) => {
  // somewhere in a middleware or in a route
  req.userId = 123
  next()
})
```

**Comment by MadRabbit** [comment]
okay, gotcha, that will work. thank you for sharing this. much appreciated!

**Comment by andrewsouthard1** [comment]
Thanks for confirming @MadRabbit - closing but let us know if you hav any other questions.

**Comment by MadRabbit** [comment]
hmm, i think there is still an issue with the suggested approach. i've tried it today and the problem with using hooks is that they are run at the end of the root cycle, so if i try to set a baggeditem in there for other request to pick that up it doesnt work, since all the requests have already happened.

can we please reopen the issue? because i still have the same questions open. how do i traverse the stack of spans and get from the currently active span in the auth middleware to the root span of the request?

i've seen that the Java library has a method to jump to the root span if needed, is there an equivalent in javascript?

**Comment by rochdev** [comment]
Does this mean you would like the root span of every service involved in the trace to have the attribute?

**Comment by MadRabbit** [comment]
Yup, that is what im trying to achieve, so that each individual service would be traceable and debuggable if that needed

**Comment by rochdev** [comment]
Is the user ID available in every service? If that's the case then baggage items wouldn't be needed and you would only need the hook in every service. Otherwise there isn't an API right now to add a baggage item for the entire request so you would have to use a private property on the `SpanContext` to access the root span from a middleware and add the baggage item to it.

**Comment by MadRabbit** [comment]
well that's the thing, services can implement authentication in different ways, some of them don't even care for a specific user. so instrumenting current user setting in every service manually dosent seem like a bright idea. id rather set the current user at the gateway level where i know what the current user is for sure, and the use the bagged item to reliably pick it up in the services.

so, the same question, is there anything you can do to help me to navigate to the root span from the auth middleware? what's the harm in making a method for that say on the span context object?

**Comment by rochdev** [comment]
The main reason why I've been holding off adding a method to access the root span is because the root span may be gone by the time you need it with asynchronous workflows where child spans can be started after their parent is finished. This is not an issue however for synchronous workflows.

Because of that, right now there isn't an official way to get the root span, but it can be grabbed from the span context since each span has a reference to the entire trace.

For example:

```js
app.use((req, res) => {
  const middlewareSpan = tracer.scope().active()
  const rootSpan = middlewareSpan.context()._trace.started[0]

  rootSpan.setBaggageItem('user-id', req.userId)
})
```

And then from that point every new child will contain the user ID in its baggage items and HTTP clients will propagate it to downstream services.

**Comment by umarkhan17** [comment]
const currentSpan = tracer?.scope()?.active();
        const rootSpan = currentSpan?.context()?._trace?.started?.[0];
        rootSpan.setBaggageItem('user-id', req.userId)

When i use started[0], baggage items are not added, but when i use started[1], they are added. I guess rootSpan is available at started[0]. @rochdev

**Comment by umarkhan17** [comment]
Is there a way to automatically add BaggageItems as tags, because for me, manually setting the tag to every span is very difficult. I would've liked if baggageItems were searchable in Datadog UI

**Comment by umarkhan17** [comment]
Or maybe we could have a configuration property which would replicated whatever is there in baggageItems as tags.

**Comment by tlhunter** [comment]
@kaievns it looks like Roch gave you a code sample workaround and that we solved this issue ages ago. I'll close the issue, but if it's still a problem then feel free to reopen.
