### ISSUE TITLE
What lib did you use to draw the diagram of datadog

### ISSUE THREAD

**Issue by xiabaiyang** [DataDog/dd-trace-js#1092]
Let me ask you a question，What lib did you use to draw the diagram of datadog? such as d3.js or other technical solution?

**Comment by rochdev** [comment]
The `dd-trace` library only deals with data collection and is not related to the UI in any way, so unfortunately I don't have an answer to this. I would suggest trying to dig into the frontend and see if you can find a drawing library in there, otherwise it may very well be in-house. Might be worth a shot to ask on StackOverflow as well if you want someone from any Datadog team to see the question.
