### ISSUE TITLE
Google pubsub plugin does not work

### ISSUE THREAD

**Issue by DavitSo** [DataDog/dd-trace-js#1099]
I'm using Datadog nodejs init tracer but didnt got traces from pubsub.

**Comment by rochdev** [comment]
The most common reason for plugins not reporting at all is initializing the tracer after the instrumented module is loaded. Is tracer initialization the very first thing happening in your app, at the top of the entry point, before any other module is imported as described in the [quickstart](https://docs.datadoghq.com/tracing/setup/nodejs/#quickstart)?

**Comment by DavitSo** [comment]
Thanks for quick response . I know about that and init tracer at first
I'm able to get http spans.
So maybe something wrong in pubsub plugin?

**Comment by DavitSo** [comment]
"@google-cloud/pubsub": {
      "version": "1.7.3"
"dd-trace": {
      "version": "0.26.0",

**Comment by DavitSo** [comment]
Sorry cant provide the code. 
I init tracer after 'use strict' )) in entry point of the project

**Comment by DavitSo** [comment]
I don't load all plugins
I'm loading only 'http', 'express', 'winston' and 'google-cloud-pubsub'
Do I need to load any other plugin?

**Comment by rochdev** [comment]
It's not recommended to disable plugins unless you are having issues since some of the plugins are necessary for the tracer to function properly. Plugins that don't have their instrumented modules loaded will have no effect.

I would recommend contacting [support](https://www.datadoghq.com/support/) because debugging this will require looking into your account to look at the traces and access to some of your code.

**Comment by DavitSo** [comment]
ok thanks
