### ISSUE TITLE
DNS tracing fail

### ISSUE THREAD

**Issue by bodinsamuel** [DataDog/dd-trace-js#1120]
**Describe the bug**
When tracing DNS, all dns.lookup call will fail 

**Environment**

* **Operation system:** macOS catalina, Kubernetes 1.16
* **Node version:** 14.13.1
* **Tracer version:** 0.26.1
* **Agent version:** 

## Repro

https://github.com/bodinsamuel/dd-trace-dns-issue

**Comment by rochdev** [comment]
It looks like an issue with promisifying `dns` methods since Node changes the return value internally because the callback version is not standard. I'm working on a fix but in the meantime I would recommend using the actual promise implementation using `dns.promises.lookup()` which should work properly.

**Comment by bodinsamuel** [comment]
Thanks for the recommendation, will try 🙏🏻
