### ISSUE TITLE
Upgrading to 0.27.0 leaks mongodb connections

### ISSUE THREAD

**Issue by rburgst** [DataDog/dd-trace-js#1133]
**Describe the bug**
After upgrading dd-trace from 0.26.1 to 0.27.0 our containers start getting timeouts when trying to connect to mongodb (after a while). The service is receiving approx 300 RPS on 4 docker containers. After being online for approx 15-20min all DB interactions become slower and slower up until the point where the healthchecks fail and containers get restarted.

**Environment**

* **Operation system:** Amazon ECS (fargate)
* **Node version:** (node:12-alpine:latest as of 2020-10-21)
* **Tracer version:** 0.27.0
* **Agent version:** docker: datadog/agent:latest (as of 2020-10-21)

**Comment by rochdev** [comment]
I will have to try to reproduce first, so I will need some more information:

* Which libraries are you using for Mongo, and which version for each library.
* What type of command is sent to Mongo? Is it mostly queries? Insert/update? Others?
* Did you upgrade Node at the same time as the tracer? There was a change in 12.19 that could theorically result in a regression for mongoose and possibly also for mongodb.

Of course if you are able to reproduce in isolation and provide a code snippet that's even better, but otherwise from the answers to the above questions I will try to replicate on my end.

**Comment by rburgst** [comment]
hi, 

### Versions

```
    "mongodb": "^3.6.2",
    "@types/mongodb": "^3.5.31",
```

### Operation types: 

* mostly queries: ```findOne, find```
* few write operations (probably 1/100 of the traffic): ```insertOne, insertMany, replaceOne, .findOneAndReplace, .deleteMany, .deleteOne```

As stated earlier we are on `node:12-alpine:latest`. This means that as of oct 17th we are on node 12.9. Note that we deploy new versions every couple of days, so we have been running on 12.9 for more than a week.

**Comment by rburgst** [comment]
Further note that I have downgraded back to 0.26.1 (and still on the same node 12.9) and everything is back to normal.

**Comment by rochdev** [comment]
Thanks for confirming. I was able to reproduce and I'm currently investigating the issue.

**Comment by rochdev** [comment]
The fix will be in the next release.

**Comment by rburgst** [comment]
I can confirm that 0.28 fixes the issue
