### ISSUE TITLE
MANUAL_DROP does not appear to work

### ISSUE THREAD

**Issue by schmod** [DataDog/dd-trace-js#1234]
**Describe the bug**

I'm attempting to use a hook in Datadog's GraphQL instrumentation to completely ignore some traces.  According to the [online documentation](https://docs.datadoghq.com/tracing/faq/trace_sampling_and_storage/#manually-control-trace-priority), I should be able to call `span.setTag(tags.MANUAL_DROP)`.

However, this does not appear to work in practice.  

Sample code:

```ts
tracer.use('graphql', {
  hooks: {
    execute: (span, args, res) => {
      if (shouldIgnore(res)) {
        span?.setTag(MANUAL_DROP, true);
      }
    },
  },
});
```

Stepping through with a debugger, it appears that [we only consider](https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/span_processor.js#L14-L27) the priority sampler for the final span in a trace, and even then, that doesn't actually appear to modify the value of `_traceFlags.sampled`.  The trace shows up in the APM web UI simply with a `manual.drop: true` tag attached:

<img width="128" alt="Screen Shot 2021-02-04 at 11 56 05 AM" src="https://user-images.githubusercontent.com/1102667/106927305-07881b80-66e0-11eb-95ba-972359c41d4f.png">

Is there some other way that I should be filtering noisy requests out of APM?

**Environment**

* **Operating system:** MacOS 11.2
* **Node version:** 14.15.4
* **Tracer version:** 0.30.5
* **Agent version:** N/A

**Comment by rochdev** [comment]
The sampling priority is locked when either every span of the trace are finished _or_ whenever any propagation happens, for example when sending a request to another service. By the time the `execute` hook runs, it's highly likely that it's too late to change the decision and it has already been locked.

To drop a trace, it should be done as soon as you know you want to drop it. Since the decision is shared on all spans within a trace, you can set the tag on any span, so you can just grab whatever span is active on the scope and set the tag there:

```js
tracer.scope().active().setTag(MANUAL_DROP)
```

It's also worth noting that if the request came from another service that is also instrumented, this service will already have made the decision and it will not be possible to change it to avoid a disconnected distributed trace.

**Comment by schmod** [comment]
@rochdev Unfortunately, moving that snippet out of the hook and into my applicaton's error-handling code doesn't appear to have helped.

Enabling dd-trace's `debug` mode, it looks like virtually the entire trace is still being sent over the wire.  

> Since the decision is shared on all spans within a trace, you can set the tag on any span

Looking at the code in `span_processor.js`, I don't think that's actually true.  Stepping through the code with a debugger, it doesn't look like I'm ever actually hitting [this snippet](https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/span_processor.js#L18-L20) in `span_processor`, which appears to be necessary for the `MANUAL_DROP` rule to actually impact the decision to send the trace over the wire.  

In the case of my specific app, it appears that the final span in my trace is often a `redis.command` span that does _not_ include the `MANUAL_DROP` tag. If I set a breakpoint there, it appears that the tag has only propagated to two spans.  

<img width="616" alt="Screen Shot 2021-02-05 at 6 32 08 PM" src="https://user-images.githubusercontent.com/1102667/107099829-ba3fa300-67e0-11eb-81be-885cc6ddd1a6.png">
<img width="1578" alt="Screen Shot 2021-02-05 at 6 30 54 PM" src="https://user-images.githubusercontent.com/1102667/107099832-ba3fa300-67e0-11eb-8216-ef7a66b3647a.png">

**Comment by rochdev** [comment]
Ah, you're right it seems that the tag cannot be set on any span, so this is a bug that we should definitely fix.

It's worth noting however that the internals of the tracer can be misleading since there are multiple sampling mechanisms. For example, `MANUAL_DROP` will still send the trace over the wire to the agent even when it works properly. This is because stats are computed by the agent, so not sending the trace is not really an option.

There are a few workarounds that I can share in the meantime but it's difficult to know what to recommend without knowing what you're trying to achieve. What is your specific use case? What are the conditions for dropping a trace?

**Comment by ameyagholkar** [comment]
+1 to having the same issue with tagging certain spans as manual drops in the `execute` hook of the `graphql` plugin.

For the specific scenario I'm working on, I'm trying to ignore all the `IntrospectionQuery` calls to the service using the example detailed [here](https://github.com/DataDog/dd-trace-js/issues/1046#issuecomment-673120268).

I'm also seeing the `{ manual: { drop: true } }` tag being set and the webUI still ends up showing the trace.

Is there another way to handle ignoring such un-needed traces?

**Comment by rochdev** [comment]
@ameyagholkar Do `IntrospectionQuery` queries make any external calls for example to other services or databases? If it doesn't then you could do it in the `execute` hook as you mentioned above once #1266 lands.
