### ISSUE TITLE
Request: Add roarr logger support

### ISSUE THREAD

**Issue by theogravity** [DataDog/dd-trace-js#1247]
https://github.com/gajus/roarr

**Comment by rochdev** [comment]
Unfortunately, roarr uses a [JSON schema](https://github.com/gajus/roarr/blob/v4.0.11/src/log.ts#L16-L36), effectively preventing us from adding out-of-the-box support since we can't add the tracing context to the message.

However, it should still be possible to do log injection for your application with a middleware that adds the tracing context to the message context instead:

```js
const log = require('roarr').child(message => {
  tracer.inject(tracer.scope().active(), 'log', message.context)
  return message
})
```

Then you could add `dd.context.trace_id` to the [reserved attributes remapping](https://app.datadoghq.com/logs/pipelines/remapping) for the Trace Id attribute.

Please let me know if that works!

**Comment by theogravity** [comment]
Thank you, that approach does work!
