### ISSUE TITLE
Send stack trace instead of single lines

### ISSUE THREAD

**Issue by Pascal997** [DataDog/dd-trace-js#1250]
Hello,

Do we have an option to tell the agent to send logs as stack trace instead of single lines?

Thanks

**Comment by rochdev** [comment]
You can find information on how to combine stack trace lines in the Datadog agent [here](https://docs.datadoghq.com/agent/logs/advanced_log_collection/?tab=configurationfile#multi-line-aggregation) and how to do it using alternative methods [here](https://www.datadoghq.com/blog/multiline-logging-guide/). However, generally speaking, we recommend using JSON instead of raw logs as they are a lot easier to parse properly and there are many standard attributes that are automatically remapped in the UI.

Since the question is about logs and not about dd-trace, I'll close this issue.
