### ISSUE TITLE
Trace header length Datadog 64 bits limit

### ISSUE THREAD

**Issue by emirot** [DataDog/dd-trace-js#1325]
As explained in this original [thread](https://github.com/DataDog/dd-trace-java/issues/2434), for now all Datadog APM (except java 0.79) are using trace id length of 64 bits.
Unfortunately, all my other systems are using a trace length of 128 bits, as it's now the default in [istio/envoy](https://github.com/istio/istio/issues/10732) and [jaeger](https://www.jaegertracing.io/docs/1.22/client-libraries/).
As a result all the traces going through that service will lose the original trace.
Is this something that could be fixed in this Datadog APM?

**Comment by rochdev** [comment]
We have partial support for B3 headers at the moment, but we don't support using _only_ B3 right now. Can you describe your use case?

**Comment by emirot** [comment]
What partial support means in this context?
My use case is I'm receiving xb3 trace of length 128 bits (as it's currently the default in istio and jaeger) and then when I was testing (in java, didn't try in javascript yet but[ the contributor told me it was across all APM )](https://github.com/DataDog/dd-trace-java/issues/2434#issuecomment-818639114) I could see that this trace was truncated to 64 bits which breaks the traceability between services.
For context, I created a a support ticket: 474435

**Comment by rochdev** [comment]
> What partial support means in this context?

It's possible to enable experimental support for B3 but it will still be using both B3 and Datadog headers separately.

> My use case is I'm receiving xb3 trace of length 128 bits (as it's currently the default in istio and jaeger)

Since the IDs are for different systems, how would it be useful to be able to propagate? Wouldn't you end up with disconnected traces in both systems, for example Jaeger and Datadog?

**Comment by emirot** [comment]
Meaning both will be sent in http headers?

What happened, as I tried in the java one, is it will truncate emitting xb3 because receiving a 128 bits but sending a 64 bits.
It might not be the case in javascript? I just want to make sure I can receive a xb3 trace of length 128 and emitting it with the same length?

I've seen that in Java:
-Ddd.propagation.style.extract=B3
-Ddd.propagation.style.inject=B3
If I remember correctly default values for these two variables are Datadog
In golang it can be done via env var: DD_PROPAGATION_STYLE_INJECT
However I don't see it specify in the [doc for javascript](https://docs.datadoghq.com/tracing/setup_overview/setup/nodejs?tab=containers)

**Comment by rochdev** [comment]
> It might not be the case in javascript?

The JavaScript implementation should not truncate the ID. It supports arbitrary size IDs when extracting, storing and injecting, and only truncates when using the ID with Datadog headers or sending to the agent. The original trace ID should stay untouched, and if this is not the case it would be a bug.

It's worth noting that right now the implementation extracts and injects everything, and prioritizes Datadog headers, meaning that if both Datadog and B3 headers are present only the Datadog headers will be read. This is because there needs to be a single tracing context from the tracer perspective. The feature is experimental however, and if this is not what you would expect definitely let me know as we are still exploring how B3 should interoperate with our own headers.

**Comment by bengl** [comment]
Hi @emirot!

It looks like this question has been answered, so I'm closing this issue. Please feel free to comment, reopen, or open a new issue if you have additional related questions or need some clarification.
