### ISSUE TITLE
clientToken is listed in the documentation but missing from the code

### ISSUE THREAD

**Issue by LoganBresnahan** [DataDog/dd-trace-js#1327]
**Describe the bug**
`clientToken` is listed as an option in the documentation https://docs.datadoghq.com/tracing/setup_overview/setup/nodejs/?tab=containers#instrumentation but is missing in the code. It should exist in https://github.com/DataDog/dd-trace-js/blob/master/index.d.ts. It looks like it was originally added back in 2019 with this commit https://github.com/DataDog/dd-trace-js/pull/730/files

Where did this go? Is it no longer supported?

**Comment by rochdev** [comment]
Good catch, that options was indeed removed but it looks like it wasn't removed from the documentation. It was used only for browser support which has since been deprecated and more recently removed completely. Browser support is now handled by RUM instead of APM. You can find more information in the [release notes](https://github.com/DataDog/dd-trace-js/releases/tag/v0.31.0).

**Comment by LoganBresnahan** [comment]
Thank you @rochdev and thank you for your work. That clears it up for me!

**Comment by bengl** [comment]
`clientToken` is now removed from the docs, so I'm closing this.
