### ISSUE TITLE
Server-side Mongodb span

### ISSUE THREAD

**Issue by bcameros** [DataDog/dd-trace-js#1332]
Hi @rochdev , question for you. At least from Node, we often view the dd-trace mongodb client spans with suspicion, since they might include client-side Node blocking time. It would be awesome to actually get a remote span from the mongodb server itself. Have you heard of any kind of support in WiredTiger or anything that would make this possible?

**Comment by rochdev** [comment]
> At least from Node, we often view the dd-trace mongodb client spans with suspicion, since they might include client-side Node blocking time.

Usually it would be an extremely small part of the span, especially since we try to instrument as close to the driver as possible so that the overhead from the integration appears in the Node service and not the MongoDB one, with the one exception being the network latency. If there is a query that is problematic for example, it should also minimize the impact of any external factors since it would become much more than the blocking code and the network.

> Have you heard of any kind of support in WiredTiger or anything that would make this possible?

Not as far as APM goes to my knowledge, but I would definitely recommend reaching out to support to confirm. There are a few cases where we have support for data stores or message queues directly, but generally speaking it's when they are implemented in Java and can use our Java agent, which is not the case for MongoDB. There is however an [agent integration](https://github.com/DataDog/integrations-core/tree/master/mongo) for it which might be helpful to correlate with the data from traces.

**Comment by bengl** [comment]
Hi @bcameros. This seems like it was answered so I'm going to close it.

Please feel free to comment or reopen or open a new issue if you have additional questions or need some clarification.
