### ISSUE TITLE
Opentracing Spec incompability: `error` tag not setting span to be failed

### ISSUE THREAD

**Issue by jizhang27** [DataDog/dd-trace-js#139]
From standard span tags on [opentracing spec](https://github.com/opentracing/specification/blob/master/semantic_conventions.md#standard-span-tags-and-log-fields), `error` tag should be ~respected to "*decide if and only if the application considers the operation represented by the Span to have failed*"~ true if and only if the application considers the operation represented by the Span to have failed. 

Currently we are relying on those three tags instead: ['error.type', 'error.msg', 'error.stack'].
 [reference](https://github.com/DataDog/dd-trace-js/blob/master/src/format.js#L46-L49)

Hope that I can get some feedback. Will be happy to make a PR for it if necessary, thanks.

**Comment by rochdev** [comment]
@jizhang27 Thanks for the suggestion! I think it does indeed make sense to support this.

Basically the `error` field would simply have to be changed to `1` when the `error` tag is `true`. I would probably discard the tag itself in the formatter since the backend uses the field and not the tag to classify errors.

Please let me know if you will make a PR to avoid duplicating the work.

**Comment by jizhang27** [comment]
@rochdev Thanks for the quick response. [PR](https://github.com/DataDog/dd-trace-js/pull/140) is created please take a look!
