### ISSUE TITLE
Question: How to add span tag to endponit resource?

### ISSUE THREAD

**Issue by dogcity** [DataDog/dd-trace-js#1405]
Hi, I am trying to add a span tag "params" to a resource "GET / project / all /: user_id" endpoint, but it adds it in a separate "anonymous" resource
The implementation of the APM I have done in this way:
```
const tracer = require ('dd-trace')
tracer.init ({
  env: process.env.NODE_ENV,
  logInjection: true,
})
```

The implementation of span tag in the trace like this:
```
router.get ('/ all /: user_id', (req, res) => {
  try {
    const params = req.params;
    const span = tracer.scope (). active ()
    if (span! == null) {
      span.setTag ('params', params)
    }
  ...
})
```

This is what I can see in the APM Traces "Live Search":
![Imgur](https://i.imgur.com/1aFclXG.png)
The span tag "params" is in an "anonymous" resource, not the main resource "GET / project / all /: user_id". I need the span tag to be in the main resource "GET / project / all /: user_id".

This is the detail of the trace of the main resource "GET / project / all /: user_id":
![Imgur](https://i.imgur.com/JV7iHIc.png)

This is the detail of the trace of the "anonymous" resource, where the span tag "params" is seen:
![Imgur](https://i.imgur.com/OggXYs5.png)

The documentation I have reviewed for nodeJs is as follows: https://docs.datadoghq.com/tracing/guide/add_span_md_and_graph_it/

I hope you can help me.

Thank you.

**Comment by winrid** [comment]
To do this, you'd have to get access to the root span.

In the context you are in, you're in a "Middleware" span.

I believe the Express plugin has "hooks" configuration to get access to the span just after creation.

As a last resort, alternatively, scope() returns a list of spans you can iterate through to find the root. Just throw up a debugger and look at that object (I believe it's in some context object).

It'd be cool if the API exposed the root span.

**Comment by dogcity** [comment]
Hello, could you give me an example? or visual guide to be able to delve into the options you give me.

Thanks.

**Comment by rochdev** [comment]
You have to use span hooks as mentioned above to avoid being in a different context such as the middleware or some other instrumented library span. It looks like our doc is wrong since it recommends simply grabbing the current active span which would always result in the behaviour you described.

Using hooks to achieve your use case would look like this:

```js
// right after tracer.init()
tracer.use('express', {
  hooks: {
    request: (span, req, res) => {
      // this will work whether `params` is a string or object
      span.setTag('params', params)
    }
  }
})
```

Make sure that both `tracer.init()` and `tracer.use()` are called before Express is imported (or more generally before anything is imported) or the configuration options might be ignored.

API docs: https://datadoghq.dev/dd-trace-js/interfaces/plugins.express.html#hooks

I will close this but please feel free to reopen if the above doesn't work or if I misunderstood your use case!
