### ISSUE TITLE
How do I send dd-trace data to DataDog if I'm not using docker? 

### ISSUE THREAD

**Issue by etiennejcharles** [DataDog/dd-trace-js#1534]
Great product guys thank you! 

I couldn't find the information about where to put my API key in If I'm not using docker - i.e 
https://docs.datadoghq.com/tracing/setup_overview/setup/nodejs/?tab=containers

I'm using the nextjs framework with an npm run dev command that starts a project on http://localhost:3000

Configuration looks like:

```js
tracer.init({
  silentMultipleInit: true,
  env,
})
```
I would have expected in the examples a way to provide an API key
A bit like 
```js
tracer.init({
  apiKey: 'some-api-key',
  silentMultipleInit: true,
  env,
})
```

Maybe my understanding is flawed about how APM is supposed to work! - 
Thanks again for the great product!

Operation system: MacOs
Node version: 13.14.1
Tracer version: 1.1.0

**Comment by rochdev** [comment]
Our APM works using an external agent process that must be installed on the host of the application that will be sending traces. The dd-trace library sends traces to the agent, which then forwards them to Datadog. The API key must be added to the agent and not to dd-trace. You can find instructions to install the agent [here](https://docs.datadoghq.com/agent/), and then you should be able to follow the rest of the Docker instructions even outside of Docker since the environment variables and configurations are the same.

The summary of the steps is:

1) Install the Datadog [agent](https://docs.datadoghq.com/agent/). I personally recommend installing it in a Docker container even locally, but otherwise there are instructions for a macOS installation.
2) Configure the agent for APM with the `api_key`, `env` and `apm_config.enabled`. You can find more information about the configuration file [here]() and an example configuration [here](https://github.com/DataDog/datadog-agent/blob/master/pkg/config/config_template.yaml).
3) Configuration should not be needed in dd-trace since it defaults to sending traces to localhost and you are installing the agent locally. This also applies to `env` which you can set on the agent instead of each application.

For `silentMultipleInit`, where did you see that configuration option? It doesn't exist in dd-trace and shouldn't exist in our docs either.

**Comment by etiennejcharles** [comment]
Thank you so much for pointing in the right direction! 

For `silentMultipleInit` it comes from the npm package `@datadog/browser-rum` - agreed it has nothing to do with the use 
case, Il leave that as a note, closing!
