### ISSUE TITLE
Release 1.2.0 includes breaking change without clear warning

### ISSUE THREAD

**Issue by jsumners** [DataDog/dd-trace-js#1578]
The v1.2.0 release notes (https://github.com/DataDog/dd-trace-js/releases/tag/v1.2.0) include:

+ aws-sdk: Update trace propagation format for aws-sdk direct invocations (#1506)

Reading through the notes on that issue, it sounds like anyone installing v1.2.0 needs to also update `datadog-lambda-js`, either across all of their Lambda functions or in AWS itself, or their traces will break. At a minimum, this should be made plainly obvious in the release notes. Ideally, this would have triggered `v2.0.0` of `dd-trace`.

Please advise if my assessment is correct.

**Comment by agocs** [comment]
Hi @jsumners , thanks for the feedback. I'm the author of #1506. The way we see it, the old behavior was based on an underlying bug in the JS and Python lambda runtimes (to wit, allowing us to write arbitrary information in `context.ClientContext.custom` rather than limiting it to `map<string, string>`). If you tried to invoke a Go or Java lambda function with the old trace context in `context.ClientContext.custom`, the downstream lambda function would not start.

This leaves us in a bad state. We want to fix dd-trace-js so that it can send trace context to any invoked lambda function. The trade-off we made was trace continuity vs customer code execution. A customer's business logic is of paramount importance to us. If Datadog is impacting the customer's ability to execute their own code, then we're doing our jobs wrong. We chose to accept incomplete traces over uncallable lambda functions.

Should this have triggered v2.0.0? Maybe. I can see the argument for it. But the argument against is that #1506
- Allows the customer to invoke Lambda functions in any runtime, as opposed to rendering dd-trace-js incompatible with Go and Java lambda functions
- Only affects the customer in cases where they are directly invoking a JS or Python lambda function
- Only breaks the trace, but allows the customer's business logic to proceed as normal
- This broken trace issue is fixable by upgrading the customer's version of datadog-lambda-js or datadog-lambda-py

You're right, this should have been better called out in the release notes, and I'm sorry for that. I will update them to contain the same info as in dd-trace-py. https://github.com/DataDog/dd-trace-py/releases/tag/v0.51.0

Do you need any help fixing the broken traces?

**Comment by jsumners** [comment]
> * Only affects the customer in cases where they are directly invoking a JS or Python lambda function

What does this mean? If I have an HTTP service that puts a message on SQS, which is then processed by a Lambda written in JavaScript, is that trace broken with v1.2.0 or not?

> * Only breaks the trace, but allows the customer's business logic to proceed as normal

I understand that, but it is still a breakage of functionality depended upon. The expectation is that the traces work and now, ceteris paribus, they don't.

> The way we see it, the old behavior was based on an underlying bug in the JS and Python lambda runtimes

I'd argue it's a bug in the Go and Java runtimes. I suspect they could have been patched to recognize the custom context as a fix in their current release lines. Then, all runtimes could have been updated to new major versions to support the coherent context.

> Do you need any help fixing the broken traces?

No. I have stopped my team from updating `dd-trace` until I am clear on this situation and how we should proceed.

**Comment by agocs** [comment]
> What does this mean? If I have an HTTP service that puts a message on SQS, which is then processed by a Lambda written in JavaScript, is that trace broken with v1.2.0 or not?

Correct, the trace is not broken in this case. This change only changes the trace propagation if you are using ['Lambda.invoke' in aws-sdk for Javascript](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#invoke-property)

https://github.com/DataDog/dd-trace-js/pull/1506/files#diff-c6e77dd2ae520de27ae8300a8d70745178d278a9f62b1b885f6d90a7a3a8c573R19-R27

> I'd argue it's a bug in the Go and Java runtimes. I suspect they could have been patched to recognize the custom context as a fix in their current release lines. Then, all runtimes could have been updated to new major versions to support the coherent context.

Irrespective of any Datadog software, It's possible to craft a [Lambda function invocation](https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html#API_Invoke_RequestSyntax) that will invoke a Node lambda function but not a Java lambda function. C.f. the `aws lambda invoke...` example in https://github.com/aws/aws-lambda-java-libs/issues/212. 

[AWS's Python docs](https://docs.aws.amazon.com/lambda/latest/dg/python-context.html) say that `client_context.custom` should be a `dict`, while the [AWS's Java library](https://github.com/aws/aws-lambda-java-libs/blob/da593256513d3cec2849bb3955ad9ec3ebf38545/aws-lambda-java-core/src/main/java/com/amazonaws/services/lambda/runtime/ClientContext.java#L25) expects clientContext to be `map<String, String>`. I did consider submitting a PR to AWS to make ClientContext more flexible, but that seemed like an uphill battle. 

> I understand that, but it is still a breakage of functionality depended upon. The expectation is that the traces work and now, ceteris paribus, they don't.
> No. I have stopped my team from updating dd-trace until I am clear on this situation and how we should proceed.

I definitely understand your concerns here. You're absolutely right to stop and ask for more information about the scope of this change. Let me know if I can help you understand anything in greater detail.
