### ISSUE TITLE
what's the difference between sampleRate and ingestion.sampleRate ?

### ISSUE THREAD

**Issue by seanyu4296** [DataDog/dd-trace-js#1584]
I noticed there is `sampleRate` and `ingestion.sampleRate`. I am not sure which is which and what does what. Can someone help to expound?

https://github.com/DataDog/dd-trace-js/blob/d6f0e322b97d5ed108036ea04de79b9d152aa8df/docs/API.md#L442-L442

https://github.com/DataDog/dd-trace-js/blob/d6f0e322b97d5ed108036ea04de79b9d152aa8df/docs/API.md#L435-L435

**Comment by rochdev** [comment]
The client sample rate (`sampleRate`) is used to control how many traces are sent from the tracer to the agent. This was added to reduce the performance overhead of the tracer in cases with very high throughput. However, it ended up having minimal impact because the biggest overhead actually comes from some of the built-in Node modules that the tracer uses and not from the tracer itself. It also has implications on metrics accuracy since they are calculated in the agent, so if traces don't make it there it can impact metrics. Because of this, we generally recommend against using this option unless absolutely necessary.

The ingestion sample rate (`ingestion.sampleRate`) controls how many traces will be ingested by the backend from the agent. With this options, all traces still make it to the agent, so metrics are still computed properly. This is the recommended option to control sampling.

Eventually the 2 options will be merged as we move metrics calculations to the tracer, which will allow to control ingestion from there, but in the meantime, generally speaking, only `ingestion.sampleRate` should be used.

**Comment by seanyu4296** [comment]
got it! thanks for the clear reply as always @rochdev
