### ISSUE TITLE
Issue with tracer.use() express hook APM

### ISSUE THREAD

**Issue by gauravsharmadev** [DataDog/dd-trace-js#1585]
**Describe the bug**
I am trying to configure my 2 services. One running in nextjs and one in typescript + express. My datadog agent is running locally. I am configuring custom span tags for each request using the following code snippet.
```
tracer.use('express', {
                hooks: {
                    request: (span, req, res) => {
                        if (is_traceable_request(req)) {
                            span.setTag('RequestURL', decodeURIComponent(req.originalUrl));
                            span.setTag('RequestQuery', req.query);
                            span.setTag('RequestParams', req.params);
                        }
                    }
                }
```
On both services. My NextJS service is successfully adding the expected span tags but typescript + express service is not even invoking the request hook callback. It would be great if you guys can help me to identify the issue or if there is something I am missing.

**Environment**
Docker
* **Operation system:**
OS X
* **Node version:**
14.15.4
* **Tracer version:**
1.1.0
* **Agent version:**
dd-agent:latest (Docker)

**Comment by gauravsharmadev** [comment]
Fixed this by removing the `tracer.init` from function to global level.

**Comment by rochdev** [comment]
@hthillman Can you try adding the hooks to `http` instead of `express`?

**Comment by hthillman** [comment]
@rochdev 

So I just tried adding some custom middleware to see if I could get a property to propagate through:

```
app.use((req, res, next) => {
  (req as any).testing = "hello";
})
```

When I log that property in the hook, it's undefined:

```
 hooks: {
    request: (span, req: any, res: any) => {
      console.warn(req.testing); // undefined
    }
  }
```

**Comment by rochdev** [comment]
@hthillman It looks like the `express` hook overrides the `http` hook, so when the hook is actually called in your example it's for the client request to the agent, and not for the incoming server request. This means that you should switch back to use an `express` hook instead of an `http` hook. However, you mentioned that it was never called when you did that, but I wasn't able to reproduce that with the above snippet and for me the hook is called properly. Do I need to change anything to the snippet so that the `express` hook is not called?
