### ISSUE TITLE
Implementation of span.log

### ISSUE THREAD

**Issue by colintoh** [DataDog/dd-trace-js#159]
Currently DatadogSpan doesn't implement the `_log` method and I don't find any way to pass in a custom `_log` method. 

1. May I know what's the current recommended practice if we wants to be able to use `span.log`?
2. Are there any future plans to implement the `_log` method?

Thanks you :)

**Comment by rochdev** [comment]
1. Right now logs should be handled by the application itself using a custom logger (i.e. bunyan or winston). There is no specific recommendation since right now `span.log` is not supported.
2. There are no plans currently to support this, but we're definitely open to it if there is added value.

@colintoh What would be the expected behavior for your use case when using `span.log`?

**Comment by colintoh** [comment]
@rochdev thanks for getting back quickly. 

Our use case 
- We want to be able to get the end-to-end debugging experience in Datadog dashboard
- span.log send logs (with span context) to the datadog dashboard (https://docs.datadoghq.com/logs/)
- Datadog APM is able to link the span with the related logs. Hence, when we want to dive deeper into the specific trace in APM, we are able to view the related logs for it

**Comment by andrewsouthard1** [comment]
Hey @colintoh - we've since added the ability to both automatically/manually inject trace ids into logs - which connect logs/traces in Datadog: https://docs.datadoghq.com/tracing/connect_logs_and_traces/nodejs Let us know if you have any questions or believe we have not covered your use case.
