### ISSUE TITLE
A way to remove DatadogSpanContext from cached promise

### ISSUE THREAD

**Issue by zen0wu** [DataDog/dd-trace-js#1737]
This is 50% a question if there's already a way, but a skim of the code suggests no.

I want to cache a promise object in some in-memory data structure, but because the existence of the async_hooks for APM tracing, the cached promise objects actually retain the DatadogSpanContext which contains a lot of things, like the request objects etc. This is essentially memory leak.

It would be great if there's a way to obtain the storage hook directly and provide an API like `AsyncLocalStorage.exit` so that this caching does not end up with leaking memory.

I might be able to grab the async_hooks by hacking into `async_hooks` module, but that feels very hacky.

**Comment by rochdev** [comment]
This is actually by design, because any continuation from that promise should be in the context of the same trace. However, there are a few mitigations in place to prevent holding too much memory, like removing all tags from the span and all references to other spans within the same trace, so generally speaking it should take very little memory.

Do you have any issues affecting your app because of this behaviour? Depending on your use case, maybe there is something that could be done automatically. If we really do need to add an API, it should probably be higher-level than direct access to the internal storage, and is something we could definitely add but it depends on your use case.

**Comment by zen0wu** [comment]
Did some additional profiling and you seem to be right, it's fairly lightweight. Closing.
