### ISSUE TITLE
opentracing dependency is causing uncaught exceptions

### ISSUE THREAD

**Issue by lmuench** [DataDog/dd-trace-js#1739]
The issue is described here: https://github.com/opentracing/opentracing-javascript/issues/172.

Locking dd-trace's `opentracing` [dependency](https://github.com/DataDog/dd-trace-js/blob/master/package.json#L78) to the previous version `0.14.5` would fix it.

**Comment by amopportunities** [comment]
major issue for us. cant deploy anything as the app crashes.

**Comment by DaedalusX** [comment]
just broke our production system. I'm having to fork to fix on our own branch to get us back up

**Comment by amopportunities** [comment]
the issue has been addressed, opentracing made a patch:
https://github.com/opentracing/opentracing-javascript/issues/172

**Comment by DaedalusX** [comment]
even if this is fixed upstream w/ opentracing, I don't see a good reason for something this critical to not have pinned deps

**Comment by lukexor** [comment]
Agreed. My team spent several hours debugging this and trying to work around it with npm overrides tonight. A pinned (or more limited) version would be preferred.

**Comment by rochdev** [comment]
The version wasn't pinned for compatibility reasons as we should be using the same version as any user-defined one for things to work properly. However, we're planning to instead move away from using `opentracing` internally and instead will provide a compatibility layer that will be compatible with all versions, so we won't need to pin a version as we won't even have the dependency anymore.

We're also currently working on reducing unnecessary dependencies in general since we can't control transitive dependencies even if the direct dependencies are pinned as lockfiles don't apply to libraries, only to the root module. More often than not, we only need a very small part of the dependency anyway, so it makes more sense to have that code within dd-trace.
