### ISSUE TITLE
Removal of config options

### ISSUE THREAD

**Issue by jamiehodge** [DataDog/dd-trace-js#1800]
Can someone please explain the rationale behind removing the enabled and debug options in favour of environment variables? We try to avoid using vars to configure packages as they can have unintended knock-on effects and are uncontrolled/untyped. Unless there is a technical motivation for the change, we'd very much appreciate their return.

**Comment by jamiehodge** [comment]
Thank you for taking the time to explain this. Your points are well-taken. I generally dislike packages changing behaviour based on environment variables because they, to a certain extent, circumvent the consuming code. That said, I can see that the tracer is special and it's not a coincidence that it ended up as an agent in Java. We would love to see the load order issue go away, especially considering that it's confusingly inverted in ruby. We currently use the `import` function to work around this issue and it makes application bootstrapping fragile and the tracer easily broken by ill-considered top-level imports. The external config file is an intriguing option if the purpose is to enforce a one-time configuration. That said, a config file is ultimately a wrapper around programmatic usage..

I think you know what you're doing here, so I'll just say thank you for the feedback.

**Comment by rochdev** [comment]
This will be possible in the future for configuring most options, but not for enabling/disable features because of the reasons mentioned above. So for this use case I think your approach makes the most sense, at least with the current API.

What is generally your use case for toggling tracing or the debug mode? If there was an API to start/stop the tracer for example, would that work for you? This would be different than the previous API in that it wouldn't unload the tracer or remove the instrumentation, and would instead just stop generating traces. Something similar could be done for debug mode as well.

**Comment by jamiehodge** [comment]
I'm going to sneak another topic into this issue, namely the service name pattern for plugins. If we are heading towards an increasingly automatic init/usage, I would wish that plugin service names defaulted to the tracer service name. The current distinction between internal and external service plugins feels arbitrary and we are writing boilerplate like this in our services:

```typescript
  tracer.use("foo", { service: config.service });
  tracer.use("bar", { service: config.service });
  tracer.use("baz", { service: config.service });
```

**Comment by rochdev** [comment]
Given the traction this issue is getting, let me provide more background around the issue.

The way that dd-trace works at a high level is by overriding `require` to be able to intercept modules as they are loaded so that they can be patched on the fly. Because of this, the tracer **must** be initialized before any external module is imported so that they go through our hooks when imported, otherwise we can't properly patch them.

Since we wanted to support programmatic configuration, we ended up adding an `init` method that has to be explicitly called. This is problematic because while this is [documented](https://docs.datadoghq.com/tracing/setup_overview/setup/nodejs/?tab=containers#adding-the-tracer-in-code), it's not really intuitive and is often misused, to the point where it's our most frequent issue reported.

Another related issue we've been getting a lot is that for some use cases similar to yours, the configuration options are not known in advance when the process is started and must be passed to the tracer programatically later on. Unfortunately, this is not supported today even with programmatic configuration available because of the load order mentioned above with `init`. For most cases the option that needed to be configured at runtime was the agent URL using service discovery, and we added a `setUrl` method for this purpose specifically, but it's not enough to cover other use cases.

For a few months now we've been planning full support for dynamic configuration, meaning that any configuration option of dd-trace can be reconfigured at any point in time. This will remove the confusion of when `init` should be called, which will also be renamed to `configure` while also keeping `init` for backward compatibility. However, some options like enabling/disabling features can still be done only when the process just started. For these options, we removed programmatic configuration and they will be applied when dd-trace is imported as opposed to when `init` or `configure` is called.

It's worth noting that even with the removal of the `enabled` and `debug` options, no functionality should be lost because it was already not supported to call `init` anywhere except at the very top of the application. While this can work in some cases and can be worked around in others, it was never officially supported to call it anywhere else but at the top of the entry point.

All this brings us to 2.0, in which we removed these options in preparation of dynamic configuration support. We preferred to do the breaking change in advance since we were already planning a 2.0 anyway, and also we wanted to identify any issues like the ones you brought to our attention before we start depending more and more on this change.

We definitely want to continue supporting as many options as possible programatically, but there are a few challenges for things like `enabled`. A few examples of what happens when dd-trace is enabled include:

* Overriding the module system, so basically `require` for CommonJS and with a loader hook for ESM, which must be done before other modules are loaded. For ESM it's even worse as the loader hook must be passed from the CLI.
* Patching supported modules as they are loaded, which is irreversible in some cases.
* Registering `async_hooks` hooks to allow context propagation, which has permanent side effects on the process like activating the tracking of async IDs even if our hook is disabled, and must be done on process start to work properly.
* Loading our code and our dependencies in memory, which is also irreversible without messing with the require cache which is not even possible with ESM.

Basically, all of this should be avoided when dd-trace is disabled because of a problem, and the only approach to safely do this is using an environment variable to never even load the code in the first place. Otherwise, any performance or stability issue could still be present even after disabling the tracer because of all the side-effects of enabling it by default in the place.

Of course there are other use cases, like disabling in specific environments to avoid additional costs. In general, we'd recommend contacting your CSM to discuss this in more details as it's best to have visibility across all environments. However, we can't ignore the fact that there are still valid reasons to want to disable the tracer completely, and it's definitely something we'd like to support programmatically, but with the various issues mentioned above, we weren't able to find one that would work for all cases while being consistent. For example, if using an environment variable prevents loading dd-trace completely, but using programmatic configuration would only disable tracing and still cause all the side-effects on the process, they are not equivalent.

Another thing worth mentioning is that if the goal is just to make sure traces don't make it to Datadog, there are a few other configuration options that can be used, for example `plugins: false` which disables all auto-instrumentation, or `sampleRate: 0` which would still send data to the agent but would have the agent drop all traces. It's also possible to set environment variables programmatically before calling `init` which would have a similar effect to the deprecated options, for example `process.env.DD_TRACE_ENABLED = false`.

With all of that in mind and the use case you provided, I definitely agree there should be a way to achieve this, but it should probably be with a separate option or some method on the public API to make it clear that it's not equivalent to enabling/disabling. I'm open to suggestions, but any solution unfortunately needs to take in consideration the limitations of how Node works.

**Comment by rochdev** [comment]
> If we are heading towards an increasingly automatic init/usage, I would wish that plugin service names defaulted to the tracer service name.

This is unfortunately a product decision and not something we can change just for Node. For what it's worth I personally agree that a service should be represented by a single service name, and I plan to write an RFC about this internally in the next few months. I'll definitely mention your comment in the RFC.

**Comment by jamiehodge** [comment]
Thank for this excellent explanation. Out of curiosity, if the loader hook is moved to the CLI with ESM, does that mean that the load order requirement on the user side will go away?

**Comment by bengl** [comment]
It looks like this has been answered so I'll close it. Feel free to comment/reopen if there's more to discuss.
