### ISSUE TITLE
Discussion: OpenTracing deprecated

### ISSUE THREAD

**Issue by tcarrio** [DataDog/dd-trace-js#1834]
**Describe the bug**

The [OpenTracing project has been archived by the CNCF][opentracing-archived], and the `opentracing` npm module which is a primary dependency for the functionality of this project [has been deprecated][opentracing-deprecated]. I don't know what this means for the maintainability of the `dd-trace` project, but I figured a discussion could be opened at least.

The suggested alternative is OpenTelemetry, which is already supported by DataDog through the [datadogexporter] project. One option might be to deprecate this package and refer users to the suggested option.

**Environment**

* **Operation system:** N/A
* **Node version:** N/A
* **Tracer version:** N/A
* **Agent version:** N/A

[opentracing-archived]: https://www.cncf.io/blog/2022/01/31/cncf-archives-the-opentracing-project/
[opentracing-deprecated]: https://github.com/opentracing/opentracing-javascript
[dd-opentelemetry-exporter-js]: https://github.com/DataDog/dd-opentelemetry-exporter-js
[datadogexporter]: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/datadogexporter

**Comment by bengl** [comment]
Hi @tcarrio. Yes, originally, this library was based on OpenTracing, and indeed the `opentracing` module. The major parts of the library we use today are the internal data structure and the public-facing API. That being said, we're in the process of replacing the internal data structure with one that more closely matches [the format sent to the Datadog Agent](https://docs.datadoghq.com/tracing/guide/send_traces_to_agent_by_api/), and it's possible we'll drop our usage of the `opentracing` module entirely and instead match the API as closely as possible, to maintain backward compatibility.

For getting trace data from a Node.js program into Datadog, `dd-trace` is the recommended solution, since it includes Datadog-specific features. Rest assured, there is a team at Datadog dedicated to maintaining it, adding new features, improving its performance, etc., and there are no plans to deprecate it.

**Comment by tcarrio** [comment]
The fact there are plans to continue support without OpenTracing is good news @bengl. Thank you for the quick reply!

**Comment by bengl** [comment]
Closing this. Please feel free to re-open if you have further related questions.
