### ISSUE TITLE
Trace doesn't follow nested Promise chain inside Promise callback

### ISSUE THREAD

**Issue by chunky-choc** [DataDog/dd-trace-js#1910]
**Describe the bug**

A trace is not produced with the following code sample:
```javascript
'use strict';

const tracer = require('dd-trace').init();

(async function main() {
    await tracer.trace('test', async () => {
        await notrace();
    });
})();

function notrace() {
    return new Promise(function(resolve, reject) {
        Promise.resolve()
            .then(() => {
                throw new Error('test');
            })
            .then(() => {
                resolve();
            });
    })
}
```

I would expect the trace to be generated with an error object contained within.

**Environment**

* **Operation system:**
* Ubuntu 20.04.2
* **Node version:**
* Node v12.22.6
* **Tracer version:**
* dd-trace 2.3.1
* **Agent version:**
* public.ecr.aws/datadog/agent:7 (2efdb068c51a)

**Comment by bengl** [comment]
@chunky-choc The problem here is that the exception is thrown inside the `then` handler for a promise that is never awaited or returned. This means that from the perspective of the async function passed to `trace`, no exception is propagated. In addition, the promise that _is_ returned is never resolved, because the exception blocks that `then` handler from running at all, and `reject` is never called. When you await a promise that never resolves, the trace lasts forever, and so it's never sent to the Datadog backend.

If you want to make the promise returned by `notrace` assume the state of the promise inside it, you can alter the notrace function to look something like this:

```js
function notrace() {
    return new Promise(function(resolve, reject) {
        Promise.resolve()
            .then(() => {
                throw new Error('test');
            })
            .then(() => {
                resolve();
            }, (e) => {
                reject(e);
            });
    })
}
```

**Comment by chunky-choc** [comment]
Thanks for looking at this @bengl.

Unfortunately, refactoring the code to connect the orphaned promise to the caller is not an option in my case - I am at a customer site and plugged in APM with the hope that tracing could provide targeted insights into the **highly legacy** codebase so that an en-masse refactor was not required.

With regards to the code sample, it seems like the tracer's scope handler is capable of following into orphaned promises, as it catches the following:
```javascript
function trace_with_error_1() {
    Promise.resolve()
    .then(() => {
        throw new Error('test');
    })
}
```

Similarly, it can follow into a Promise callback
```javascript
function trace_with_error_2() {
    return new Promise(function(resolve, reject) {
        throw new Error('test');
    })
}
```

It seems like the failing case is when the above two are combined. Is following the scope into the nested, orphaned promise an impossibility or an oversight?

**Comment by chunky-choc** [comment]
Apologies, this is my bad.

I just checked the contents of the trace in the first sample and it doesn't actually record an error. I'd opened this on the (incorrect) belief that if the tracer can do A and it can do B, then why not A and B together.

Thanks for looking into it @bengl.
