### ISSUE TITLE
Redis multi() weirdness

### ISSUE THREAD

**Issue by msiebuhr** [DataDog/dd-trace-js#218]
We're using redis' `multi().<functions>.exec()` in quite a few places - and they show up in somewhat weirdly in traces:

![screen shot 2018-08-08 at 08 42 26](https://user-images.githubusercontent.com/330611/43820711-50872866-9ae7-11e8-98b9-371557bf5a51.png)

```javascript
redisConnection.multi()
    .getset(sessionKey, newNonceValue)
    .expire(sessionKey, sessionExpiry)
    .exec(callback);
```

Given that the docs for [multi](https://redis.io/commands/multi) / [exec](https://redis.io/commands/exec) mentions the commands in between as a queue, I would expect it to be represented along these lines:

```
| multi / exec --------------|
  | getset ---| | expire --|
```

**Comment by rochdev** [comment]
From my understanding of multi/exec, the start times are correct since all commands are sent to Redis right away. For example, `MULTI` is sent starting a transaction at the server, then `GETSENT` is sent, then `EXPIRE` is sent, and finally `EXEC` is sent, notifying Redis to execute the queued commands atomically. All of this happens synchronously.

For the duration (and thus the end time) I also think this is correct. Technically, before the entire atomic operation is executed, there is no way to know if `GETSET` and `EXPIRE` are actually done as the transaction could simply be rolled back.

Please let me know if you think my understanding is incorrect.

**Comment by rochdev** [comment]
Closing for now. Please feel free to reopen if you still think the behavior is incorrect.
