### ISSUE TITLE
Traces split in express plugin after v2 upgrade

### ISSUE THREAD

**Issue by kuritz** [DataDog/dd-trace-js#2204]
**Expected behaviour**
The full trace, with all spans, from beginning of a request to the end, are viewable as one trace.

**Actual behaviour**
Most of our traces are being split into 2 parts within the spans generated by the express plugin. This happens most of the time, but not all of the time. For the majority of the traces that are split, the first half of the trace always shows an express middleware as the last span.

Full trace:

<img width="958" alt="Screen Shot 2022-07-20 at 6 00 53 PM" src="https://user-images.githubusercontent.com/15093505/180090055-756e610e-6ad8-4dfb-9c0f-de56479b5f22.png">

First half of a broken trace:

<img width="954" alt="Screen Shot 2022-07-20 at 7 21 24 PM" src="https://user-images.githubusercontent.com/15093505/180098883-959ae627-540d-4664-8070-f9cd588b1dc3.png">

**Steps to reproduce**
We upgraded from 1.6.0 to 2.9.1.

**Environment**

* **Operation system:** debian bullseye (docker)
* **Node.js version:**  14.19.3
* **Tracer version:** 2.9.1
* **Agent version:** 7.37.1
* **Relevant library versions:**
```
"express": "^4.17.2"
```

**Notes**

We opened a support issue about a month ago in regard to this bug.

**Comment by rochdev** [comment]
> We opened a support issue about a month ago in regard to this bug.

Do you have the ticket number for your support case? I want to make sure we're tracking both in parallel to avoid confusion.

> This happens most of the time, but not all of the time

Is this something you're able to constantly reproduce, and can you share a reproduction snippet? This is likely due to a change that happened a few versions ago where we no longer force our own context to be active on middleware. This is because it would alter the existing context which wouldn't play well with existing user defined `AsyncLocalStorage` instances. This does mean that if anything breaks the asynchronous context within a middleware, the tracer will now also be impacted when it used to not be. A reproduction would make it easy for us to identify what is losing the context, but otherwise, it should also be doable on your end with a debugging session with a watch on `require('dd-trace').scope().active()` to find when it becomes `null` during the request to identify the offending line.

I'll still try to think of a better way to handle this on our end, but generally speaking we shouldn't be altering any existing asynchronous context, so instead the underlying issue of losing the context should be addressed.

**Comment by kuritz** [comment]
Thanks @rochdev ! This context is really helpful.

> This does mean that if anything breaks the asynchronous context within a middleware, the tracer will now also be impacted when it used to not be. 

The ticket number is `843761`

I think it'll probably be a bigger lift to reproduce in an example rather than track it down in app, so I'll take a hack at debugging it first.

**Comment by kuritz** [comment]
The traces break on `POST` but not `GET` and the reason seems to be because they are breaking at the point we parse the JSON body of the request with `express.json()`.

**Comment by kuritz** [comment]
I've been unable to locate where the span becomes `null` thus far to confirm this, but the pattern noted above is consistent on the website. The last span on any trace triggered by a `POST` is always the json parsing middleware. I have yet to find a `GET` that exhibits the same behavior, the traces always include all spans from the request.

<img width="961" alt="Screen Shot 2022-07-22 at 9 30 53 AM" src="https://user-images.githubusercontent.com/15093505/180450232-175634c2-16c9-4761-92fb-8f8d2f5845d7.png">

**Comment by rochdev** [comment]
I see in the [release notes](https://github.com/expressjs/body-parser/releases/tag/1.20.0) of the latest version of `body-parser` that they fixed an issue with the async hooks context being lost. Can you try with that version to see if it fixes the issue? I'll work on a fix on my end as well to support older versions but at least if it works it will unblock you.

**Comment by kuritz** [comment]
Good catch! Yes, looks like we are 1 minor behind. I'll try to update now.

**Comment by kuritz** [comment]
Upgrading to express 4.18.x did fix this issue for us. Thanks again for all the help! As far as we're concerned, this issue can be closed. I'll leave that up to you though, it's not clear to me how long this bug has existed in the express `body-parser` module and what the impact of that might be on dd-trace-js users.
