### ISSUE TITLE
Express and GraphQL plugins not loading inside Docker

### ISSUE THREAD

**Issue by lucasfronza** [DataDog/dd-trace-js#2310]
When we run our Express app locally (e.g. `ts-node server.ts`), both `express` and `graphql` plugins are loaded. But, when we build and run inside a docker container (as runs when deployed to production), it doesn't load these two plugins.

For the built version, we build our application using Webpack (setting `dd-trace` as external, as recommended in the docs). Then, in our Dockerfile, we install `dd-trace` and `datadog-lambda-js`, copy the built output, and run the application.

**Expected behaviour**
dd-trace `init` loads Express and GraphQL plugins when running inside docker container
i.e. we want startup logs to show `integrations_loaded": ["http", "net", "dns", "express", "graphql", "http2"],`

**Actual behaviour**
when running inside docker container, startup logs show `"integrations_loaded":["http","net","dns","http2"],`

**Environment**

* **Operation system:** MacOS (for local `ts-node`) / node:16-alpine (Docker)
* **Node.js version:** 16
* **Tracer version:** 2.11.0, 3.0.0 (tested with these two versions)
* **Relevant library versions:** datadog-lambda-js@6.81.0

Any insights on that? Thank you! 😊

**Comment by bengl** [comment]
Hi @lucasfronza. Please try adding `express` and `graphql` as external.

**Comment by rochdev** [comment]
Generally speaking, for instrumentation to work properly, all instrumented modules should be external. The easiest way to make sure that all of them are covered is to externalize all `node_modules` with [webpack-node-externals](https://www.npmjs.com/package/webpack-node-externals). Since dd-trace relies on patching `require` to intercept modules and instrument them, any bundled module won't be instrumented.

**Comment by lucasfronza** [comment]
Hey!
That was indeed the issue! Setting modules as external fixed it. 😁
Thank you both!! 🙏
