### ISSUE TITLE
vitest support for CI

### ISSUE THREAD

**Issue by nertzy** [DataDog/dd-trace-js#2366]
[vitest](https://vitest.dev/) is a new test framework similar to Jest that runs on top of Vite.

It would be great if dd-trace-js could instrument vitest similar to how the Jest integration works.

**Comment by andrei-ivanov-pie** [comment]
+1 on the request please.

**Comment by paulvidal** [comment]
👍  on this one

**Comment by tainmar** [comment]
🙏

**Comment by Cellule** [comment]
:+1: vitest is gaining more and more traction as a replacement of jest.
We recently-ish had to switch away from jest because of performance issues and vitest was the easiest/simplest switch.
Now that we're starting to look into datadog CI integration, I really wished there was native support for vitest

**Comment by nullfame** [comment]
Today I was wondering "why did my tests stop showing up in Datadog" and I realized it is because I haven't published a repo that uses jest in several weeks. All my most recent code is using vitest. It is basically a must for the Vue framework and the support for module syntax is superior. And performance. So fast

I am an every day Datadog user. This will not stop me from using Datadog but I will not be able to make full use of CI. Using vitest is more necessary to my workflow than seeing it in Datadog

**Comment by opeologist** [comment]
adding another comment here to request support

**Comment by juan-fernandez** [comment]
hi everyone! Good news: this is currently being worked on in https://github.com/DataDog/dd-trace-js/pull/4415. It's still going to take a bit but vitest support is coming 😄

**Comment by juan-fernandez** [comment]
🎉 🚢 vitest support is now released in 
* https://github.com/DataDog/dd-trace-js/releases/tag/v5.18.0
* https://github.com/DataDog/dd-trace-js/releases/tag/v4.42.0

**Comment by juan-fernandez** [comment]
until we update the docs with the instructions, here's how you can try the vitest integration: 

```
npm install --save-dev dd-trace
```
Make sure the `dd-trace` installed version is >=5.18.0 or >=4.42.0.

Then run your vitest tests passing `NODE_OPTIONS='--import dd-trace/register.js -r dd-trace/ci/init'`.

⚠️ **Important**:
* It needs an extra parameter when compared to running tests with `mocha`, `jest` or other supported test frameworks: `--import dd-trace/register.js`
* The minimum supported Node.js versions are >=18.19 and >=20.6

For example, if your `package.json` looks like:
```json
"scripts": {
  "test": "vitest run"
}
```

Run 
```
NODE_OPTIONS='--import dd-trace/register.js -r dd-trace/ci/init' DD_SERVICE=your-javascript-app-tests npm run test 
```

Take into account that you'll still need an API key or a running agent (see [docs](https://docs.datadoghq.com/tests/setup/javascript/?tab=vitest#configuring-reporting-method) for more info)

**Comment by thuringia** [comment]
@juan-fernandez Thanks for the amazing work getting this done! Does this mean, we can also use `vitest` to report code coverage now as well?

I doesn't look like it works, at least running `vitest` with the `istanbul` coverage provider, or via `nyc` doesn't show something in the details for a test session. Uploading a `junit` report works as expected, unfortunately it's not possible to annotate an existing test session, so that's not an alternative.

**Comment by juan-fernandez** [comment]
> @juan-fernandez Thanks for the amazing work getting this done! Does this mean, we can also use `vitest` to report code coverage now as well?
> 
> I doesn't look like it works, at least running `vitest` with the `istanbul` coverage provider, or via `nyc` doesn't show something in the details for a test session. Uploading a `junit` report works as expected, unfortunately it's not possible to annotate an existing test session, so that's not an alternative.

thanks for the feedback @thuringia ! It's indeed impossible at the moment to report code coverage to datadog if you're using `vitest`. I'll make sure this is reflected in the docs. It's in our roadmap to support it though, so expect it to happen. I'll announce it in this thread as well 😄

**Comment by karrui** [comment]
Is there an open issue to track code coverage through `vitest`? When will it be supported?

**Comment by juan-fernandez** [comment]
@karrui total code coverage for `vitest` is available since https://github.com/DataDog/dd-trace-js/releases/tag/v5.21.0 and https://github.com/DataDog/dd-trace-js/releases/tag/v4.45.0. My bad for not announcing it here as I promised 😅

**Comment by juan-fernandez** [comment]
ℹ️ docs are updated too 😄 : https://docs.datadoghq.com/tests/code_coverage?tab=javascripttypescript#vitest

**Comment by karrui** [comment]
Thx! does `v8` coverage work? does not seem to pipe coverage to datadog.

**Comment by juan-fernandez** [comment]
yeah, it should work. Feel free to open an issue. It'll be much easier to fix a potential issue with a reproducible case 😄

**Comment by karrui** [comment]
This is the [PR](https://github.com/opengovsg/starter-kit/pull/332), I'm able to share it since it's open sourced!

**Comment by juan-fernandez** [comment]
> This is the [PR](https://github.com/opengovsg/starter-kit/pull/332), I'm able to share it since it's open sourced!

thanks! That's helpful

**Comment by DominicPeters95** [comment]
Any updates on this?

**Comment by DominicPeters95** [comment]
This command worked for me: 
`NODE_OPTIONS="--import dd-trace/register.js -r dd-trace/ci/init --max-old-space-size=4096" vitest run --coverage --pool threads`
