### ISSUE TITLE
Automatic `node-redis` instrumentation not working

### ISSUE THREAD

**Issue by alejandro-delgado-garcia** [DataDog/dd-trace-js#2397]
**Expected behaviour**

To see spans being created for Redis commands running in my app

**Actual behaviour**

Redis spans are not being automatically created

**Steps to reproduce**

**Environment**

* **Operation system:** alpine
* **Node.js version:** 16.14.2
* **Tracer version:** 2.13.0
* **Agent version:**
* **Relevant library versions:**
    * node-redis 4.1.0

On the other hand, I use another package that uses `ioredis` and the spans are created correctly so the issue seems to be related to `node-redis`.

**Comment by rochdev** [comment]
It looks like `@node-redis/client` moved to `@redis/client` since 4.1.0, which we don't currently instrument. We'll have to add support, which should be straightforward since the code didn't change between both packages, but in the meantime if it's feasible for you it should be possible to downgrade to 4.0.6.

**Comment by alejandro-delgado-garcia** [comment]
> It looks like `@node-redis/client` moved to `@redis/client` since 4.1.0, which we don't currently instrument. We'll have to add support, which should be straightforward since the code didn't change between both packages, but in the meantime if it's feasible for you it should be possible to downgrade to 4.0.6.

Good to know. Thank you for the update! I will keep an eye on this repo to check once the update is available
