### ISSUE TITLE
[profiling] Collect the number of samples

### ISSUE THREAD

**Issue by zen0wu** [DataDog/dd-trace-js#2444]
Google Chrome's profiler has this issue where, when looking at a particular function/line that takes a long time, it's really hard to differentiate
between
- High number of calls with small cost
- Single number of calls with large cost

Currently dd profiling has the same problem. It would be great that we can add the "number of samples" to the flamegraph, that'd really help a huge ton with our profiling.

**Comment by rochdev** [comment]
Unfortunately the number of samples wouldn't help much, since both cases would result in exactly the same number of samples because sampling is done every ~10ms regardless of if the function was exited and reentered or not. Basically this is a general problem with profiling and not something we can fix, at least not short term without a completely custom profiler or an entirely new profiler added to Node or V8.

**Comment by zen0wu** [comment]
Thanks for that explanation, I think I understand a bit better now! You're basically saying that because the profiler works by inspecting the call stack every ~10ms, it's by no means measuring the actual # of calls to that function.

I thought firefox profiler has the # of samples hence assumed it was useful information.

I guess to get real tracing capabilities, what we really need is to have something like, dtrace/ebpf support, which node has been lacking compared to other languages, unfortunately. Actively waiting on https://github.com/nodejs/node/issues/44550 to happen...

I'll be closing this one out, thanks again.
