### ISSUE TITLE
Allow configurable OPERATION_NAME for pg plugin (maybe all plugins?)

### ISSUE THREAD

**Issue by clarkdave** [DataDog/dd-trace-js#292]
We've found that Datadog's APM interface can be confusing if a single service has traces with multiple operation names. In the Datadog UI, a "service" is actually represented by this URL: `https://app.datadoghq.com/apm/service/$service/$operation_name`

Where `$service` could be `postgres` and, in this library, `$operation_name` would be `pg.query`.

The operation name is currently a hardcoded constant in most, maybe all plugins, e.g. in the pg plugin: https://github.com/DataDog/dd-trace-js/blob/master/src/plugins/pg.js#L5

## Why make them configurable

In Datadog's UI, if a single service is ever supplied traces with more than one operation name, only the first reported operation name is shown by default in the UI. Other operations need to be accessed by adding them into the URL manually. There's also no "top level" overview that shows all the traces (with different operation names) under the same service. i.e. if you visit `https://app.datadoghq.com/apm/service/$service` it's a 404 page, not, as might be expected, a list of operations/traces with different operation names.

For us, we have a top level `postgres` service which we instrument from both Ruby and Node.js. The Datadog APM gem in Ruby instruments postgres queries using the `postgres.query` operation name, whereas the `dd-trace-js` module in JS instruments them with `pg.query`.

## Solution

If we can configure the operation name for all plugins, anyone providing traces for the same service from multiple languages (e.g. Ruby and JS) can ensure they're all using the same operation name and are thus grouped together in the APM interface.

I think an even better solution, though one out of scope for this particular repo, would be for The Datadog APM UI to treat "operation name" as a first-class citizen in the trace hierarchy. Then the operation name could be used to further segment traces under a service, whilst still providing a way to see them all at the top level.

**Comment by rochdev** [comment]
There are actually 2 problems causing this issue. I will address them individually.

1. Different operation names between Node and Ruby

This is a bug as our integrations in the different tracers should have the same operation name for the same operation. In this case for example, both represent a "PostgreSQL query" and thus should be consistent. Given the overall issue that you've described above, changing this now could have a high impact, so while it definitely should be fixed in the future, right now it depends on the second problem being solved first.

2. Support for multiple top-level operation names

To comment on your proposed solutions:

> If we can configure the operation name for all plugins, anyone providing traces for the same service from multiple languages (e.g. Ruby and JS) can ensure they're all using the same operation name and are thus grouped together in the APM interface.

I don't think this should be configurable. One of the goals of the integrations is specifically to make configuration like this unnecessary. If there is an inconsistency, it should be reported and addressed, not worked around. Also, there are integrations with multiple top-level names, which would make configuration more difficult. There is also the processing pipeline that is coming in a future version that will allow to change anything on the trace before it's sent to the agent.

Would it be a possibility to have 2 different service names for `postgres` in the 2 services? For example `foo-postgres` for `foo` service, and `bar-postgres` for `bar` service. This is also the default for the integration. While not ideal, this would be a way to separate your operations from different services until multiple top-level names are implemented (see below).

> I think an even better solution, though one out of scope for this particular repo, would be for The Datadog APM UI to treat "operation name" as a first-class citizen in the trace hierarchy. Then the operation name could be used to further segment traces under a service, whilst still providing a way to see them all at the top level.

This is actively being addressed. It could take some time however.

**Comment by rochdev** [comment]
Closing this as operation names are now first-class citizens and there can be multiple operation names for each service as described in your ideal solution. Please feel free to reopen if you are still having any issues.
