### ISSUE TITLE
Cypress tasks to manually force flush of tracer

### ISSUE THREAD

**Issue by AMEntwistle** [DataDog/dd-trace-js#3222]
We have been running into compatibility issues with dd-trace and other cypress plugins and sometimes we see that the datadog trace is not sent before cypress exits. It would be great to have a cypress task that allows us to force the flush of the tracer to ensure we have sent all traces before we exit. Something like the below:

` 'dd:flushTraces': () => {
      return new Promise(resolve => {
      tracer._tracer._exporter._writer.flush(() => resolve(null))
})`

**Comment by juan-fernandez** [comment]
hey! Thanks for reporting this issue. 

The code to do exactly this should already be in place: https://github.com/DataDog/dd-trace-js/blob/master/packages/datadog-plugin-cypress/src/plugin.js#L321-L331. 

When returning a promise in the `after:run` event, like we do, cypress should wait for it to resolve before shutting down: https://docs.cypress.io/api/plugins/after-run-api#Usage. Now that I read the docs it says

> before Cypress proceeds running your specs.

which is confusing because `after:run` should be the last event before shutting down, so I wonder if there's a bug in there. 


What versions of cypress and dd-trace are you seeing this behavior in? A small reproducible case would be very useful too 😄

**Comment by AMEntwistle** [comment]
Hey,

So the plugin works fine listening to the `after:run` event. However the issue comes in when you use additional plugins. Cypress has a limitation where you can only have a single listener per event and they will overwrite the event of the plugin. 

We have a private plugin (which unfortunately I cannot share) which also uses this event and is overwriting the DD-trace listener. This is why it would be great to have a way to manually trigger the flush through a cypress task so we could have control of the process.

Unfortunately I can't provide a working example :(

**Comment by juan-fernandez** [comment]
oh wow, I didn't know of that limitation. That's quite bad 😓 . 

I think the better solution here is likely to expose the `after:run` handlers so you can do something like: 

```javascript 
import ddPlugin from "dd-trace/ci/cypress/plugin"
improt otherCypressPlugin from "other-cypress-plugin"

export default defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      ddPlugin(on, config)
      otherCypressPlugin(on, config)
      on('after:run', (...args) => {
        return ddPlugin.afterRun(...args).then(() => {
          return otherCypressPlugin.afterRun(...args)
        })
      })
      return config
    },
```

having a `'dd:flushTraces'` task isn't great, because invoking it in the wrong moment (like before a test session is finished) might lead to hard to detect bugs. On the other hand, exposing `afterRun` makes it clear that it needs to happen at `after:run`

**Comment by AMEntwistle** [comment]
Yes it can be quite frustrating.

That does seem like a good idea!

**Comment by Devstored** [comment]
@AMEntwistle You can use this plugin : https://github.com/elaichenkov/cypress-plugin-init/
