### ISSUE TITLE
OpenAI Tracer Throws Exception When Using Streaming

### ISSUE THREAD

**Issue by patricker** [DataDog/dd-trace-js#3385]
**Expected behaviour**
datadog-plugin-openai handles trace of text completion calls without error

**Actual behaviour**
datadog-plugin-openai throws exception during tracing. 

**Steps to reproduce**
Enable response streaming.
I'm using Langchain, and if I enable streaming, I get the error, and if I disable streaming the error goes away.

**Environment**

* **Operation system:** OSX
* **Node.js version:** 20.2
* **Tracer version:** 4.6.0
* **Agent version:**
* **Relevant library versions:**

```
/node_modules/dd-trace/packages/datadog-plugin-openai/src/index.js:504
  tags['openai.response.choices_count'] = body.choices.length
                                                       ^
TypeError: Cannot read properties of undefined (reading 'length')
    at commonCreateResponseExtraction (/node_modules/dd-trace/packages/datadog-plugin-openai/src/index.js:504:56)
    at responseDataExtractionByMethod (/node_modules/dd-trace/packages/datadog-plugin-openai/src/index.js:308:7)
    at OpenApiPlugin.finish (/node_modules/dd-trace/packages/datadog-plugin-openai/src/index.js:181:5)
    at node_modules/dd-trace/packages/dd-trace/src/plugins/tracing.js:25:12
    at Subscription._handler (/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:14:9)
    at Channel.publish (node:diagnostics_channel:142:9)
    at /node_modules/dd-trace/packages/datadog-instrumentations/src/openai.js:32:20
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (/node_modules/p-retry/index.js:50:12)
```

**Comment by tlhunter** [comment]
During my initial research it appeared that the OpenAI Node.js library itself didn't officially support streaming responses. But, the library does make it possible to specify in the request that you want to stream the response and also allows you to write your own code in userland to handle the streamed response.

Streaming support wasn't added to the integration due to this lack of official support, but the integration certainly shouldn't be throwing an error like you're encountering.

I'll work on a fix to prevent streamed responses from erroring.

**Comment by patricker** [comment]
Thanks @tlhunter! Looking forward to a fix and appreciate your support.

**Comment by tlhunter** [comment]
A PR that should fix this is ready, but it will take a couple days to merge and deploy. In the meantime you should be able to prevent your app from crashing using `DD_TRACE_DISABLED_INSTRUMENTATIONS=openai`.
