### ISSUE TITLE
Koa integration: resource tagging by route only works for routes defined by koa-router

### ISSUE THREAD

**Issue by leoyu037** [DataDog/dd-trace-js#350]
A lot of our node-koa apps serve single page webapps that do client-side routing, so they don't use `koa-router`. When this is the case, it's hard to distinguish requests for the main payload with requests for other static assets in the APM UI. 

For example in our "contacts" app, both main payload requests and static asset requests get bucketed into the same `GET ` resource that doesn't have a route associated with it:

<img width="1915" alt="screen shot 2018-11-05 at 10 29 20 am" src="https://user-images.githubusercontent.com/1095664/48008612-05d9e280-e0e8-11e8-90fc-249a67002e7b.png">

Both types of traces are commingled in this resource:

Static asset request:
<img width="1917" alt="screen shot 2018-11-05 at 10 29 36 am" src="https://user-images.githubusercontent.com/1095664/48008774-4cc7d800-e0e8-11e8-9277-8b5332f43a68.png">

Main payload request:
<img width="1919" alt="screen shot 2018-11-05 at 10 44 51 am" src="https://user-images.githubusercontent.com/1095664/48008784-52252280-e0e8-11e8-8761-c37506ecd270.png">

**Comment by leoyu037** [comment]
Specifically, we use `koa-heartbeat` and `koa-static-server`

**Comment by KempfCreative** [comment]
This is a major pain point for my team as well. I would love some documentation using the official libraries which explains how to implement custom resource endpoints.

**Comment by rochdev** [comment]
There are a few options depending on the specific case:

##### koa-heartbeat

In this case, since it's only a heartbeat I assume what is wanted is to ignore these routes. This can be done with the `blacklist` option of the tracer which will stop tracing these routes:

```js
tracer.use('koa', {
  blacklist: ['/healthz']
})
```

##### Custom or unsupported routers

In this case the route can be added manually in a span hook:

```js
tracer.use('koa', {
  hooks: {
    request: (span, req, res) => {
      span.setTag('http.route', req.myCustomRoute)
    }
  }
})
```

##### koa-static-server

In this case, it's not really possible to provide a relevant value since there is no route. Using the URL is not really a good option since the cardinality would be really high and the produced data would not really be valuable. If you know that there is a finite number of known static assets that do not vary a lot, then it would be possible to use the hook from above as if it was a route.

We could definitely document all of this better, but otherwise it should be possible to achieve the end goal with the existing constructs.

Please let me know if this helps!

**Comment by rochdev** [comment]
Closing as there is no way to do this out of the box without a router that we can patch, and solutions for individual use cases were provided above.
