### ISSUE TITLE
dd-trace in jest empties array

### ISSUE THREAD

**Issue by lodmfjord** [DataDog/dd-trace-js#3504]
We are using dd-trace 3.29.1

**Expected behaviour**
Arrays should be left as is.

**Actual behaviour**
Arrays get shifted, making them empty in the end.

**Steps to reproduce**
See for example this test:
https://github.com/island-is/island.is/blob/main/apps/services/auth/delegation-api/src/app/delegations/test/me-delegations.access-incoming.spec.ts

The array expected gets emptied making tests fail when using dd-trace.

We patched this by changing this line:

``` 
const testParameters = parametersByTestName[testName].shift()
```
 
 to

```
const testParameters = parametersByTestName[testName][0]
parametersByTestName[testName] = parametersByTestName[testName].filter((e, index) => index !== 0)
```

**Comment by juan-fernandez** [comment]
hey @lodmfjord! Thanks for reporting! The array that gets shifted is internal so it shouldn't surface at all. What error do you see? Can you point me to some instructions to reproduce the error?

**Comment by oskarols** [comment]
@juan-fernandez Hi 👋 

We're also seeing this issue since we've updated from an older version of `dd-trace` to v2.51.0.

We're using:
- Node 16.19.0
- jest 29.1.2
- babel-jest 29.6.2

The smallest reproducible test case I could come up with is this:

```
const array = ['a', 'b']

describe('test', () => {
  it.each(array)('tests the length of the array', () => {
    expect(array).toMatchInlineSnapshot(`
    [
      "a",
      "b",
    ]
    `)
  })
})
```
![image](https://github.com/DataDog/dd-trace-js/assets/324147/b346ad67-7595-4fac-99da-9534f2debff9)

It seems the array is being `.pop()`:ed by each iteration of the inner test. Curiously it seems changing the 'tests the length of the array' string to also contain '%s' will make the test pass. 🤔 

I manually went through the versions of `dd-trace` to find where this regressed. It seems this was in 2.7.0.

**Comment by lodmfjord** [comment]
I can confirm what @oskarols says. I added a proxy on the object and found out dd-trace was shifting the array, so that is why I patched it by creating a new array.

**Comment by lodmfjord** [comment]
You can see the patch here @oskarols:
https://github.com/island-is/island.is/blob/main/.yarn/patches/dd-trace-npm-3.29.1-4e4e5d3a0c.patch

**Comment by juan-fernandez** [comment]
thanks! This is very helpful. I'll investigate and see what I can do. I'll give you updates

**Comment by juan-fernandez** [comment]
https://github.com/DataDog/dd-trace-js/pull/3526 this PR should fix this issue 😄
