### ISSUE TITLE
skip exprses static file  trace

### ISSUE THREAD

**Issue by wanglong167** [DataDog/dd-trace-js#400]
skip exprses static file  trace

**Comment by rochdev** [comment]
Duplicate of #350. While it's a different framework, the same [resolution](https://github.com/DataDog/dd-trace-js/issues/350#issuecomment-597403709) applies. Basically, the paths can be blocklisted if known in advance, or otherwise the trace can be dropped in a span hook with `span.setTag('manual.drop')`.
