### ISSUE TITLE
How to trace jest with custom environment

### ISSUE THREAD

**Issue by lughino** [DataDog/dd-trace-js#4164]
Hi there,
I need to use a custom environment as I need a newer version of jsdom, so I imported the new `@jest/environment-jsdom-abstract` package and created a custom environment that extends from that class:

```js
const JSDOM = require('jsdom');
const BaseEnv = require('@jest/environment-jsdom-abstract').default;

class JSDOMEnvironment extends BaseEnv {
  constructor(config, context) {
    super(config, context, JSDOM);
  }
}

module.exports = JSDOMEnvironment;
module.exports.default = JSDOMEnvironment;
```

Unfortunately, I did not get that working. I always get this error:
```bash
/Users/lughino/ui/node_modules/dd-trace/packages/datadog-plugin-jest/src/index.js:228
      this.testSuiteSpan.setTag(TEST_STATUS, status)
                         ^

TypeError: Cannot read properties of undefined (reading 'setTag')
    at /Users/lughino/ui/node_modules/dd-trace/packages/datadog-plugin-jest/src/index.js:228:26
    at Subscription._handler (/Users/lughino/ui/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:14:9)
    at Channel.publish (node:diagnostics_channel:56:9)
    at /Users/lughino/ui/node_modules/dd-trace/packages/datadog-instrumentations/src/jest.js:591:27
    at runTestInternal (/Users/lughino/ui/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/Users/lughino/ui/node_modules/jest-runner/build/runTest.js:444:34)
```

To initiate the `dd-trace` I tried to use the `dd-trace/ci/init` through NODE_OPTIONS, or simply including it in this test env file like `require('dd-trace').init();`.
None of my attempts made it work.

The jest settings are:
```js
const baseConfig = {
  testEnvironment: require.resolve('@internal/jest-preset/jsdomEnv.js'),
  testRegex: '\\.test\\.(js|tsx?)$',
  testMatch: null,
}
```

If I switch to `testEnvironment: 'jsdom'` everything works properly.
I also tried to copy the exact content of the old `jest-environment-jsdom` package inside this custom file but I always get the same error.
It seems like there is some sort of logic around those test environments that prevents me from using tracing in a custom environment.

Any help would be very appreciated

**Comment by juan-fernandez** [comment]
hey @lughino ! Thanks for the report. 

My first thought was that you could extend directly from `jest-environment-jsdom` (as they with node in the [jest docs](https://jestjs.io/docs/29.6/configuration#testenvironment-string)) but from what I see in the source, JSDOM is hardcoded: https://github.com/jestjs/jest/blob/9113f44b459f96db31e5ad3811d4d8b07f79e54f/packages/jest-environment-jsdom/src/index.ts#L17, so that's not an option for you. 

Sadly I don't think there's any workaround for you, as we only monkey patch `jest-environment-jsdom` and `jest-environment-node`: https://github.com/DataDog/dd-trace-js/blob/a60bd2475b9e9abb7a7be2c4b3732eeaa3634104/packages/datadog-instrumentations/src/jest.js#L296-L304

This said, I think adding support for `@jest/environment-jsdom-abstract` wouldn't be too hard (famous last words). Would you be interesting in contributing the change? I can help 😄
