### ISSUE TITLE
Difficulties adding TAGS to test executions in CI Test Visibility

### ISSUE THREAD

**Issue by MaximilianoAdaro** [DataDog/dd-trace-js#4221]
### Description

I am encountering difficulties with adding **tags** to **test executions** in Datadog `CI Test Visibility`. Despite following the available documentation and attempting various methods, the tags I specify do not seem to be applied to the test runs as expected. This issue is impacting our ability to effectively filter and manage test results based on custom criteria.

### Expected Behaviour

After test execution, I expect to see the custom tags applied to each test run in Datadog CI Test Visibility, allowing for efficient filtering and management based on these tags. Apart from the ENV and SERVICE variables.

### Environment

- `dd-trace` version: v4.30.0
- CI/CD tool used: GitHub Actions

Thank you for your assistance!

**Comment by MaximilianoAdaro** [comment]
@juan-fernandez could you please help me with this issue?

**Comment by juan-fernandez** [comment]
> @juan-fernandez could you please help me with this issue?

hey @MaximilianoAdaro ! 

Could you give me details about what you're trying? What test framework you're using and how you're adding custom tags. As always, a small reproducible case would be awesome 😄

**Comment by MaximilianoAdaro** [comment]
Thank you for the quick response @juan-fernandez ! Here are the additional details:

**Test Frameworks Used:**
- Cypress
- Playwright

**Method of Adding Custom Tags:**
I am adding custom tags by specifying them in the GitHub Actions environment variables, using the `DD_TAGS` alongside `DD_ENV` and `DD_SERVICE`, which are working as expected. My goal is to apply these custom tags to all test executions to enhance filtering capabilities in the Datadog dashboards. 

Here is an example of how I define these environment variables in my GitHub Actions workflow:

```yaml
env:
  DD_ENV: staging
  DD_SERVICE: my-service
  DD_TAGS: team:myteam,feature:myfeature
```

**Expected Display in Dashboards:**
I expect that these custom tags (`team:myteam`, `feature:myfeature`) will appear alongside the automatically applied `env` and `service` tags in the Datadog CI Test Visibility dashboards. This should allow us to filter test executions based on these custom criteria directly from the dashboard interface.

Hope this clarifies my approach. Thank you for your help!

**Comment by MaximilianoAdaro** [comment]
Or probably with Node Labels? Let me try

**Comment by juan-fernandez** [comment]
> ```yaml
> DD_TAGS
> ```

that's weird because we test just that in https://github.com/DataDog/dd-trace-js/blob/master/integration-tests/cypress/cypress.spec.js#L292-L293

did you check for those tags at the test detail view? You need to go at the `Other tags` section: 
<img width="167" alt="Screenshot 2024-04-05 at 16 55 51" src="https://github.com/DataDog/dd-trace-js/assets/22798219/2f3212c1-6ee6-489d-8b68-8557cd36ea26">

You might just be missing the creation of the facet: 
<img width="423" alt="Screenshot 2024-04-05 at 16 58 12" src="https://github.com/DataDog/dd-trace-js/assets/22798219/125b39ba-f7cb-4573-a782-e46ac3554a2f">

I've just tested this manually and I think it works as intended

**Comment by MaximilianoAdaro** [comment]
Got it, I haven't seen the `Other tags` tab, thank you so much Juan for the quick help!
