### ISSUE TITLE
Sampling priority not working?

### ISSUE THREAD

**Issue by joaovieira** [DataDog/dd-trace-js#491]
In our app we've got a healthcheck endpoint that is pinged every 20sec or so from the ELB. This is causing this resource to be picked for sampling way more than normal requests (just trying on Staging, so not a real production load).

I've been trying to set the `sampling.priority` of healthcheck resources to be rejected, as they're not useful, so we get more space for other resources to be sampled (as mentioned [here](https://docs.datadoghq.com/tracing/advanced_usage/?tab=nodejs#priority-sampling)).

I have set:

```ts
tracer.use('express', {
  hooks: {
    request: (span, req: Request) => {
      // Ignore/reject traces for healthcheck endpoint.
      if (req.route.path.includes('healthcheck')) {
        span.setTag(tags.SAMPLING_PRIORITY, priority.USER_REJECT);
      }
    },
  },
});
```

However healthcheck resources are still being sampled even though they've got the `sampling.priority` tag set as `-1`. And other relevant resources do not appear as they're not "complete".

![Screen Shot 2019-03-18 at 11 59 33](https://user-images.githubusercontent.com/474603/54528604-59511c80-4975-11e9-9897-addb0692cf3e.png)

![Screen Shot 2019-03-18 at 11 57 08](https://user-images.githubusercontent.com/474603/54528614-5eae6700-4975-11e9-9763-fef3e0ef2179.png)

Is my thinking/approach correct in trying to reject samples for this resource? And why is it not working?

**Comment by rochdev** [comment]
The sampling priority is locked depending on a few conditions, which most likely have already happened when the hook runs (it runs at the end of the request). Setting a value after it's been locked is ignored, which is why this approach doesn't work.

There are a few ways to handle this depending on the behavior you are looking for:

1) If you want to drop the local trace, but propagate the existing decision to other services (for example if you call another service in your health check and want that trace to be available), use the `blacklist` option of the `express` plugin. For example `tracer.use('express', { blacklist: '/healthcheck' })`
2) If your service is not calling any other services in the health check, then use the approach described above since it's the simplest approach.
3) If you are calling other services and want to drop the entire distributed trace, then set the sampling priority tag in a middleware that runs before any other middleware on the `healthcheck` path.

Let me know if any of these work for you!

**Comment by joaovieira** [comment]
It does say the `_spanContext._isFinished` is false, so I guess it's still not done at that point. That endpoint does not call any external service, but I guess it propagates the trace to the base service (`express.middleware`) before the hook and that's what is locking it. Fair.

What is the side-effect of blacklisting? Would it ignore `/healthcheck` completely, ignoring throughput, errors, etc.?

**Comment by rochdev** [comment]
> It says the _spanContext._isFinished is false, so I guess it's still not finished at that point.

If there was any propagation, the value is still locked regardless of the state of the spans.

> What is the side-effect of blacklisting? Would it ignore /healthcheck completely, ignoring throughput, errors, etc.?

Yes, blacklisting will drop the trace at the client level, and stats are calculated by the agent, meaning they will not be included. If you want to keep the stats, you should instead use option `3`.

**Comment by joaovieira** [comment]
Yeah, that's what I understood as well. Thanks a lot! 

Closing.
