### ISSUE TITLE
Determine if span is being sampled at runtime.

### ISSUE THREAD

**Issue by codeitcody** [DataDog/dd-trace-js#506]
I would like to determine if the active span is being sampled. If I know the current span is being sampled I want to include additional logging that I normally don't record.

In my production system I am only sampling 1% of my traces, but it would be nice to have additional logging in the 1% I do sample. I don't want this additional logging in non-sampled traces due to high log volume.

I see SpanContext has a `_sampled` boolean that appears to be what I want and I can access it like this:

```
if (span.context()._sampled) logger.info('Some additional detail.')
else logger.debug('Some additional detail.')
```

It appears that `_sampled` is meant to be a private field (even though the above code works because JavaScript doesn't protect them) so I was wondering if this field can be exposed publicly from an `isSampled()` accessor?

**Comment by rochdev** [comment]
`dd-trace` is an implementation of OpenTracing, so our API is basically the OpenTracing API. `span.context()` is meant as a mean for vendors to include their own metadata on the span, which may be public or private depending on the vendor's needs. In our case, we didn't expose anything as public as we are trying to have maximum interoperability with OpenTracing.

For now I would say to use `_sampled` as like you said it's not truly private. I'll see if we can add something like `isSampled()`, but in any case, in general we will put a note in release notes whenever `span.context()` fields changed as we know some fields are used by users already.

**Comment by rochdev** [comment]
May I ask why you use client sampling? This is usually a last resort feature when you get very high loads and the tracer is impacting your ability to scale. We usually prefer to sample later in the pipeline to ensure stats/etc are correct.

**Comment by codeitcody** [comment]
I understand keeping to the OpenTracing spec. Thanks for the feedback.

We are doing client sampling as our app is serverless/FaaS on AWS Lambda Azure Functions. I like to start a parent span on each function invocation so I can trace it and its child spans to function completion. Basically doing the same thing the `express` plugin does but per function instead of per URL.

**Comment by rochdev** [comment]
How do you send the traces? Do you use an agent in your infrastructure?

**Comment by codeitcody** [comment]
Sorry - see my edit above.

We use an external DD agent which multiple function apps are streaming to.

**Comment by rochdev** [comment]
> We could set it on the agent for sure, but this adds some complexity to our deployment.

Not necessarily. We have a feature called Priority Sampling which allows controlling sampling on the agent from the tracer. In general, the defaults are enough since it automatically adjusts according to the load, but it's possible to override it as well.

This would be the preferred approach for a few reasons:

* Traces are always complete since the sampling decision is distributed across services.
* Stats are calculated by the agent, so they are only correct if the agent receives the trace.
* You can eventually benefit from Trace Search & Analytics even for dropped traces.

See https://docs.datadoghq.com/tracing/advanced_usage/?tab=nodejs#priority-sampling

I know I'm scope creeping a bit here, but I think there are enough benefits to using Priority Sampling that it would be beneficial to use it for your use case.

In any case, for now depending on what kind of sampling you decide to use, the following 2 properties are available on the context:

* For client sampling, `span.context()._sampled` as you previously mentioned.
* For priority sampling, `span.context()._sampling.priority` which is >0 when kept or <=0 when dropped.

**Comment by codeitcody** [comment]
This is very neat. Thanks for pointing me towards it. I appreciate the help @rochdev!

**Comment by andrewsouthard1** [comment]
We've since moved to a tail based sampling model with Tracing Without Limits: https://docs.datadoghq.com/tracing/tracing_without_limits/ , if you have any questions please feel free to reopen.
