### ISSUE TITLE
assumed that scope.activate(span, sync fn) would finish the span

### ISSUE THREAD

**Issue by kevinburkenotion** [DataDog/dd-trace-js#515]
I expected that this code from the test suite:
 
```javascript
scope.activate(span, () => 'test')).to.equal('test')
```

Would mark the span as finished. The test suites don't really indicate that you need to explicitly finish the span either.

**Comment by rochdev** [comment]
What would you recommend to make this clearer?

**Comment by kevinburkenotion** [comment]
One solution would be to finish the span. I don't know that folks are passing a sync function to span.activate and expecting it to be alive after, though maybe they are.

**Comment by rochdev** [comment]
The scope manager only manages an asynchronous context scoped to a function. Its responsibility is only to propagate the span within that scope, but not to manage the span lifecycle. My question was mostly how we could make that clearer in either the documentation and/or the API.

We do have different APIs that handle the span lifecycle however, but they only handle very specific asynchronous constructs since in JavaScript there are so many ways to do that.

See [Tracer.trace()](https://datadog.github.io/dd-trace-js/interfaces/tracer.html#trace) and [Tracer.wrap()](https://datadog.github.io/dd-trace-js/interfaces/tracer.html#wrap)

**Comment by rochdev** [comment]
Closing this since using the scope manager is now documented in the [API docs](https://datadoghq.dev/dd-trace-js/#scope-manager) and is considered advanced usage. `tracer.trace` and `tracer.wrap` should be preferred for most cases which handle the span lifecycle, context propagation, and errors.
