### ISSUE TITLE
unfinished child span results in silent failure

### ISSUE THREAD

**Issue by kevinburkenotion** [DataDog/dd-trace-js#516]
If you fail to finish a child span, Datadog will fail to publish any APM traces. Further there's no evidence of this in published metrics (along other keys) or console logs or messages in the Datadog dashboard or different application behavior, unless you run with `debug: true` turned on. This spits out a ton of data to the point of being unreadable; it would have been easy to miss the child span stack trace.

See also #515.

**Comment by kevinburkenotion** [comment]
Figuring out why this was broken cost us almost an entire workday, not to mention all of our API trace metrics were broken.

**Comment by rochdev** [comment]
There is a warning in the debug logs when a parent span is finished before its children. As you said, this is not ideal for 2 reasons:

- With a high volume of logs, the log entry may not be noticed.
- You need to enable debug mode to see these, but then you create tons of logs which causes the previous point.

We are currently working on replacing this log with metrics as you've mentioned. The specific metrics that will be available will show you how many finished and unfinished spans are dangling in memory. If this number increases, you will be able to drill down to find the exact name of the span that is kept in memory.

We will also be adding logs in a few cases outside of debug mode. This should allow to at least know that there is an issue, and then debug mode will be used only to get more details.

Please let me know if that would work for you. Of course you've already lost a lot of time because of this, but hopefully this will prevent future occurrences.

**Comment by kevinburkenotion** [comment]
That would be a good start, as long as it's noted in enough places in the logs, and added to e.g. the Debugging section of the docs.

**Comment by rochdev** [comment]
> That would be a good start, as long as it's noted in enough places in the logs

What do you mean by "noted in enough places in the logs"?

> and added to e.g. the Debugging section of the docs.

This will definitely be added to some debugging or troubleshooting section of the docs.

**Comment by rochdev** [comment]
Closing since runtime metrics are now available which include the number of unfinished spans.
