### ISSUE TITLE
API to determine whether span is finished

### ISSUE THREAD

**Issue by kevinburkenotion** [DataDog/dd-trace-js#517]
Even if I had thought to test the span being finished in #515 it's not really clear how to do so, you can call `finish()` but there's no public API for determining whether a span is finished or not.

**Comment by rochdev** [comment]
What is the use case to validate if the span has been finished? Also note that it's safe to call `span.finish()` multiple times as additional calls are simply ignored.

**Comment by kevinburkenotion** [comment]
The use case to validate is avoiding a situation where I fail to close a child span and my company loses APM trace metrics for about 4 hours while I frantically debug the situation.

**Comment by rochdev** [comment]
In this case, having to manually check every span through an API would still result in lost time trying to figure out which span is at fault. I prefer to implement your recommendation in https://github.com/DataDog/dd-trace-js/issues/516 where metrics will be used to determine exactly how many spans for each operation are unfinished.

Do you think this would be sufficient? Otherwise, what additional constructs would you propose?

**Comment by rochdev** [comment]
Closing since runtime metrics are now available which include the number of unfinished spans and it should not be otherwise needed to check if a span is finished.
