### ISSUE TITLE
sampleRate setting does not affect allocation

### ISSUE THREAD

**Issue by kevinburkenotion** [DataDog/dd-trace-js#543]
Shortly after a recent deployment we began seeing reduced throughput, increased latency and CPU spikes.

Tracing through afterwards it turns out the cause was an increase in the number of calls to datadog.trace(). The size of a given trace object went from 6kb to about 40kb. It was pretty difficult to see this though without turning on debug. I would not have expected the average engineer to be able to figure out what was going wrong.

The documentation seems to indicate that reducing the sample rate is a solution to load issues on servers with heavy load. However, tweaking the sample rate did not solve the throughput problem. Even setting to 0 or 0.01 still allocated new spans and new memory and triggered increased GC, behavior I was not expecting to see; I was expecting a decrease in the sample rate to decrease the number of objects being allocated.

**Comment by rochdev** [comment]
The problem is that if a span is not sampled, this information needs to be propagated to any child spans in some way. However, in this case instead of creating actual spans, we could probably just create an empty shell with the sampling information.

I'll take a look at what we can do to address this, especially since as you said the feature in its current state fails to address the very use case it was created to address.

**Comment by rochdev** [comment]
One thing I would like to know also however is what kind of CPU/memory impact are you getting? In general we also want to optimize the tracer so using sampling is not needed in most cases.

**Comment by kevinburkenotion** [comment]
Roughly a 30% hit to the number of requests per second and a 50% increase in P95 latency

**Comment by rochdev** [comment]
This is definitely more than our goal. I will reimplement sampling in a way that reduces significantly the overhead of dropped traces. If you are interested to help us improve the product, I could also work with you to try and reduce our overhead by investigating what causes such an overhead for your specific service.

**Comment by rochdev** [comment]
Just a quick update to mention I have a fix in the works which will reuse a no-op span instead of creating new spans. This should greatly improve the performance impact since it will not do any allocations. I will try to have it finished for the next release.

In the meantime, can you provide a CPU profile that I could look at to try and find why your performance impact is so high? Feel free to DM me on Slack if the profile data is sensitive.
