### ISSUE TITLE
Plugins not setting span components

### ISSUE THREAD

**Issue by schancel** [DataDog/dd-trace-js#546]
Currently plugin span services are being overriden as such:

https://github.com/DataDog/dd-trace-js/blob/a2fcaea0f07d2deca31c93ee4c5b8640d93c9ede/src/plugins/pg.js#L17

However, per the opentracing [spec](https://github.com/opentracing/specification/blob/master/semantic_conventions.md#span-tags-table) they should set the component tag.

**Comment by rochdev** [comment]
We can set the `component` tag in addition, but we still need to have a different service name for now since stats are calculated by service.

**Comment by schancel** [comment]
What do you mean "stats are calculated by service?"  They are not calculated by operation name?

**Comment by rochdev** [comment]
Some stats are by operation name, but in general most of them are only calculated by service, hence the different service name by integration. We are actively working on improving this however so that this will no longer be necessary in a future version.

Of course the current behavior also has the assumption that you actually want the stats for every integration. This may not be true in which case you can safely rename the services right away.

**Comment by rochdev** [comment]
Closing as metrics will now be calculated for every non-internal components regardless of service name when #1363 lands in 0.34.
