### ISSUE TITLE
Not picking up pg integration

### ISSUE THREAD

**Issue by lwakefield** [DataDog/dd-trace-js#549]
`dd-trace` does not seem to be picking up the `pg` integration. No special configuration is done of `dd-trace-js` out of the box. I have a suspicion that it may have something to do with our usage of `knex` - but am not certain.

```
dd-trace: 0.10.4
pg: 7.10.0
knex: 0.12.7
```

Let me know what more debugging information I can provide.

If any owners/authors know of any "hints" as to where to start looking, I would be happy to debug further.

**Comment by rochdev** [comment]
Since you are using a supported version of `pg`, I would suspect an issue with the import order. See https://docs.datadoghq.com/tracing/setup/nodejs/#quickstart

In short, the tracer must be initialized *before* any instrumented module. When using `import` statements, this means also moving the tracer initialization to a different file to avoid hoisting.

**Comment by lwakefield** [comment]
Thanks @rochdev - I suspect that is in-fact the issue. I'll close this for now, and reopen if needed.

:)
