### ISSUE TITLE
question about async_hooks span references

### ISSUE THREAD

**Issue by vfernandestoptal** [DataDog/dd-trace-js#618]
I suspect we have a memory leak related to dd-trace on a project I'm working on.

After trying to track it down, I'm seeing some weird stuff related to this code:
https://github.com/DataDog/dd-trace-js/blob/v0.12.1/packages/dd-trace/src/scope/async_hooks.js#L22

I'm seeing:
1. undefined values being stored for some `asyncId`s
2. spans being stored which have `isFinished` value set to `true`
3. same span object reference being stored multiple times under different `asyncId`s

I haven't been able to identify the exact conditions that cause this.

Question 1: are any of these 3 cases normal "expected" behavior?
Question 2: does removing these keys from the `_spans` hash have any impact on dd-trace operation? (assuming they have already been submitted to agent)

**Comment by rochdev** [comment]
> 1. undefined values being stored for some asyncIds

This can happen when a new scope is bound to the current active span but there isn't one.

> 2. spans being stored which have isFinished value set to true

This happens because scope management is unrelated to the span lifecycle. This means that both finished and unfinished spans can be activated on a scope. The only way for the span to be freed from the scope is for the async resource referenced by the scope to be destroyed.

> 3. same span object reference being stored multiple times under different asyncIds

This can happen if a function is bound to a span, or if a new async resource is created from within an existing async resource execution which will then inherit the scope.

> Question 1: are any of these 3 cases normal "expected" behavior?

All 3 would be considered expected behavior.

> Question 2: does removing these keys from the _spans hash have any impact on dd-trace operation? 

This should definitely not be done in general, but you know your app best so if you know after a specific point a span will never be needed again it should be safe to remove it. However, this is definitely a workaround for an actual problem. If a scope is held in memory along with its span because of async resources, it means there is an existing memory leak in the application where some async resources are not destroyed. The tracer makes the issue worse because it's holding the trace in memory as well, which may be a lot bigger than the async resource itself.

If this is causing stability issues for you, then definitely implement the workaround if it can prevent crashes. However, I would recommend to investigate what is holding the async resources in the first place.

**Comment by vfernandestoptal** [comment]
Hey, thanks for the fast reply.

I played around with the tests for the net plugin (looked like a simple one with small number of methods/dependencies) and I'm seeing references in the `_spans` and `_types` after all the tests are done, similar to what we have in our project.

Here's a screenshot of the tests output and a link to the code changes that I added:
![Screenshot from 2019-07-08 21-10-21](https://user-images.githubusercontent.com/20822057/60839814-fd313300-a1c5-11e9-9f2c-0d99edfd137c.png)

https://github.com/vfernandestoptal/dd-trace-js/commit/9ef349ccc29a4ea7b926adb43881a889ff40b69b

Do you have any additional insights into that? Maybe if I can understand why this happens, it would help track down the code causing our issues.

**Comment by rochdev** [comment]
There is actually a lot going on in the tests, so it may make it more difficult to figure out.

What is the actual issue you are having with the application? What async resources do you see held in memory?

**Comment by vfernandestoptal** [comment]
I've activated the runtime metrics and the async resources that were consistently growing were TCPWRAP and TLSWRAP types.

![image](https://user-images.githubusercontent.com/20822057/60958117-bf372a80-a2fd-11e9-8bf9-da949ef24c22.png)

Meanwhile, we've also deployed with an updated nodemailer version and this https://github.com/nodemailer/nodemailer/pull/990 fixed the issue. It's been running stable since then.

Thanks @rochdev for your help and pointing us in the right direction!!
