### ISSUE TITLE
Mongo traces no longer showing

### ISSUE THREAD

**Issue by lwakefield** [DataDog/dd-trace-js#697]
**Describe the bug**

We recently upgraded some mongo dependencies:

```
FROM: 
    "mongodb": "^2.0.49",
    "mongoose": "^4.13.17",
    "mongoose-deep-populate": "^1.1.0",
TO:
    "mongodb": "^3.3.1",
    "mongoose": "^5.2.13",
    "mongoose-deep-populate": "^3.1.1",
```

Since that upgrade - mongo traces have stopped showing in APM.

~I am testing an upgrade to `dd-trace-js` in case that fixes the issue.~ No luck with the upgrade.

~Additionally I am in the process of testing the order in which dependecies are loaded to make sure `dd-trace-js` is still initialized first.~ It appears that dd-trace-js is still initialized before everything else.

**Environment**

* **Operation system:** Heroku Dyno
* **Node version:** 10.x
* **Tracer version:** 0.15.3
* **Agent version:** Heroku Buildpack

**Comment by rochdev** [comment]
It looks like since `mongodb` 3.3.0 they have merged `mongodb-core` which is thus no longer a standalone library. Since we instrument `mongodb-core` which no longer exists, the plugin is never used. We'll need to update the plugin to support the new merged project. If you do not have a strong reason to use >=3.3.0, I would recommend downgrading in the meantime. This should be fixed in the next few days.
