### ISSUE TITLE
Async/Await Manual Tracing

### ISSUE THREAD

**Issue by Shikkic** [DataDog/dd-trace-js#704]
We've been using automated koa tracing for a few weeks now with pretty good coverage, however we're trying to do some manual tracing and we've been having trouble creating a custom span within a function block that has an async/await call in it. 

I feel as though the documentation surrounding manual instrumentation is a bit lacking. I do see one area where it acknowledges await specifically:

> Note: async/await cannot be bound and always execute in the scope where await was called. If binding async/await is needed, the promise must be wrapped by a function.

However there is no working example on how to deal with await. For reference the following is something we're looking to to trace. We just want to know how long it took for the await to take essentially.

```js
const span = tracer.startSpan("article.request");
span.setTag("http.uri", `advice/${receivedUri}`);
tracer.scope().activate(span);
const response = await api.posts.get.byUri(`advice/${receivedUri}`);
span.finish();
```

Is there something particularly wrong with the code sample, something I missed or am just doing wrong?

**Comment by rochdev** [comment]
> I feel as though the documentation surrounding manual instrumentation is a bit lacking.

The documentation is definitely confusing right now 😅We are reworking it to have everything in one place which should make everything easier to understand.

> However there is no working example on how to deal with await.

There are a few ways to handle this for your use case:

##### OpenTracing API + Scope Manager

This is our low-level API that is based on OpenTracing with a few extensions like the scope manager.

```js
const span = tracer.startSpan("article.request");
span.setTag("http.uri", `advice/${receivedUri}`);
const response = await tracer.scope().activate(span, () =>
  api.posts.get.byUri(`advice/${receivedUri}`)
);
span.finish();
```

Reference: https://datadog.github.io/dd-trace-js/#scope-manager

##### Datadog API (trace)

This is our high-level API that also handles scope activation and the lifecycle of the span. In this example you don't need to manually activate the span on the scope or to finish it since it's handled internally.

```js
const tags = { "http.uri": `advice/${receivedUri}` }
const response = await tracer.trace("article.request", { tags }, span =>
  api.posts.get.byUri(`advice/${receivedUri}`)
)
```

Reference: https://datadog.github.io/dd-trace-js/interfaces/tracer.html#trace

##### Datadog API (wrap)

This is identical to `tracer.trace()` but it returns a new function instead of calling its callback directly. If the snippet you provided is the entire function for example, you could wrap it.

```js
const getPosts = tracer.wrap("article.request", receivedUrl => {
  tracer.scope().active().setTag("http.uri", `advice/${receivedUri}`)
  return api.posts.get.byUri(`advice/${receivedUri}`)
})
```

Reference: https://datadog.github.io/dd-trace-js/interfaces/tracer.html#wrap

In general however, this is something that should already be done out-of-the-box by the tracer since it looks like this is a call to an external service. Are you having any issues with our automatic instrumentation?

**Comment by Shikkic** [comment]
Thank so much for responding so quickly @rochdev, this was a huge help. I believe we're able to see the custom span now.

> In general however, this is something that should already be done out-of-the-box by the tracer since it looks like this is a call to an external service. Are you having any issues with our automatic instrumentation?

What we currently do have is the `net` package being auto-instrumented and that produces some traces for outbound requests to some APIs. However the only information we get from that is the `tcp.connect` traces, which I believe is only for how long it takes to establish the connection, not the duration of the request, which is what we really need to see. Unless I'm misunderstanding what that trace is?

<img width="1515" alt="Screen Shot 2019-10-04 at 2 21 09 PM" src="https://user-images.githubusercontent.com/8765687/66230502-50762d00-e6b2-11e9-920d-2dd50e4ccd96.png">

**Comment by rochdev** [comment]
> However the only information we get from that is the tcp.connect <url> trace/span, which I believe is only for how long it takes to establish the tcp connection, not the duration of the request

Correct. Since a TCP socket can be long-lived, it's not possible to know when each request sent through the socket actually starts and ends, unless we have a specific library or protocol that we can instrument.

What is the library that is used to make the call? What protocol is it using? If it's an open-source library, then we should be able to support it out-of-the-box. We are trying to keep manual instrumentation only for custom code that cannot otherwise be automatically instrumented whenever possible.

**Comment by Shikkic** [comment]
We're using Axios (https://github.com/axios/axios) to make HTTP requests.

**Comment by Shikkic** [comment]
That would be fantastic if we could have it be automatically traced.

**Comment by rochdev** [comment]
Axios uses `http` which should be instrumented out-of-the-box. Can you confirm that you are not seeing the outgoing HTTP requests? If that's the case it's definitely a bug. It's also possible that the `http` module is required somewhere before the tracer which would cause it to not be instrumented.

**Comment by Shikkic** [comment]
Ah that would explain a lot, I have all default plugins disabled by default. If it wasn't apparent I'm the same person from this issue (https://github.com/DataDog/dd-trace-js/issues/652). So my tracer setup is a bit custom to get around webpack. I'll enable the `http` module and configure the instrumentation for it and see what happens. Thanks!

**Comment by Shikkic** [comment]
That worked beautifully @rochdev, it's a real game changer for us thank you!

The only question I have left would if there is a way to rename the http service name? Right now it shows up as this.

<img width="481" alt="Screen Shot 2019-10-04 at 4 38 17 PM" src="https://user-images.githubusercontent.com/8765687/66238402-8f61ae00-e6c5-11e9-89c3-e4b93817cf85.png">

**Comment by Shikkic** [comment]
I've tried doing something like:

```js
tracer.use("http", { enabled: true, service: "service-name" })
```

but that didn't seem to work, I feel like I might have to manually override the service value somehow since the tracer setup is really custom 😞

**Comment by Shikkic** [comment]
I wasn't able to quite figure out how to rename the service but I'm not super worried about. I'll close this, no need for it to be hanging open. Thanks for your help again!
