### ISSUE TITLE
Configuration option to disable middleware instrumentation

### ISSUE THREAD

**Issue by countcain** [DataDog/dd-trace-js#764]
Hi,

Whenever I enabled the dd-trace in the express based node project, I can see a lot of resources that have been tracked automatically. Most of them are express middleware and they are overlapped with the resources that discovered by the express plugin. For every http request coming in, there will be a suite of spans of these resources tracked which creating distractions.

Is there a way that I can stop tracking them?

![Screen Shot 2019-11-27 at 2 17 38 PM](https://user-images.githubusercontent.com/1751150/69753453-a4851700-1121-11ea-8d12-81886a23998c.png)

![Screen Shot 2019-11-27 at 2 28 46 PM](https://user-images.githubusercontent.com/1751150/69753780-5ae8fc00-1122-11ea-9565-11fecfca9762.png)

Thanks

**Comment by rochdev** [comment]
In the UI on the left you should have an Operation Name filter. If you uncheck `express.middleware` you will stop seeing any span with that operation name, and the resources for these will also stop appearing in the Resource filter.

Given the above, I don't necessarily recommend to completely stop tracking them since you would lose visibility into the middleware, and if one of them is slow or throws errors it would be more difficult to find the source of the issue.

If you really don't want to ever see middleware spans at all, please let me know and we'll add a configuration option to disable middleware instrumentation.

**Comment by countcain** [comment]
@rochdev First of all, thanks for your quick response! Indeed, I can use filters/controls to have a clean APM UI with things/metrics that we want to track on a daily basis. But we do hope you can provide a configuration option to disable middleware instrumentation. That will be very appreciated.
