### ISSUE TITLE
Can't see customised span

### ISSUE THREAD

**Issue by zhaoyi0113** [DataDog/dd-trace-js#803]
**Describe the bug**

I am using below code to send customised span to datadog but I am not able to see it. There is no error in the log. Is this something wrong with the code I am using?
```
      const span = tracer.startSpan('call-quote-server');
      const timeout = setTimeout(() => {
        ...
        span.finish();
        reject(new Error(errorMsg));
      }, REQ_RES_TIMEOUT);
      receiver = (data) => {
         ...
          span.finish();
          resolve(data);
        }
      };
```

**Environment**

* **Operation system: alpine
* **Node version:  ** v12.13.1
* **Tracer version:** 0.16.3
* **Agent version:**

**Comment by rochdev** [comment]
At a glance it looks fine, although you could add the error to the span once this works properly.

Are you creating only this span alone, or is it part of an existing trace in for example a web request? If it's part of an existing trace, is the entire trace missing or only the span?

**Comment by zhaoyi0113** [comment]
I am running the nodejs application with `Apollo` and `express`. 
And finally I find the span which appears at the top drop down list. But I can't open it which is not a primary operation. So the problem is that my span is added as a primary operation which is not what I expect. How can I create the span in the http request chain? 

![image](https://user-images.githubusercontent.com/3355579/70957431-3604fa80-20ca-11ea-8412-de0e7d207ff7.png)

**Comment by rochdev** [comment]
You would have to add the parent span to your custom span by grabbing it from the current scope which will add it to the trace as a child of that span. This can be done with something like this:

```js
const childOf = tracer.scope().active();
const span = tracer.startSpan('call-quote-server', { childOf });
```

As mentioned above, you also would need to manually add the error to the span as well by using:

```js
const error = new Error(errorMsg);
span.setTag('error', error);
reject(error);
```

However, this code could benefit from a new API that is not yet documented that would make the code simpler since it manages this for you, especially when using promises.

For example:

```js
// parent span automatically added by tracer.trace()
const promise = tracer.trace('call-quote-server', () => {
  return new Promise((resolve, reject) => {
    const timeout = setTimeout(() => {
      ...
      // span automatically finished by tracer.trace()
      // error tag automatically added by tracer.trace()
      reject(new Error(errorMsg)); 
    }, REQ_RES_TIMEOUT);
    receiver = (data) => {
      ...
      // span automatically finished by tracer.trace()
      resolve(data);
    };
  });
});
      
```

References:
- https://datadog.github.io/dd-trace-js/#scope-manager
- https://datadog.github.io/dd-trace-js/interfaces/tracer.html#trace

**Comment by rochdev** [comment]
One question that I have is that given the name `call-quote-server` it looks like this is calling another service, which should already be auto-instrumented out of the box. Are you using a library or protocol that we don't support?

**Comment by zhaoyi0113** [comment]
I didn't know there is `childOf` attribute on `startSpan` method. Will `tracer.scope().active()` throw error  If there is no parent scope?

**Comment by zhaoyi0113** [comment]
> One question that I have is that given the name `call-quote-server` it looks like this is calling another service, which should already be auto-instrumented out of the box. Are you using a library or protocol that we don't support?

It sends an event via web-socket to another service. Could you explain more about `auto-instrumented`? How does it work?

**Comment by rochdev** [comment]
If there is no parent it will return `null`, in which case the child will simply be orphaned similar to the behavior you are currently having, but it will not cause issues with the app.

**Comment by rochdev** [comment]
> It sends an event via web-socket to another service. Could you explain more about auto-instrumented? How does it work?

I mean for example like `express` which just works out of the box without custom spans. However, we unfortunately don't support websockets out of the box yet so that explains while you have to rely on custom instrumentation.

If you want to propagate context so that all your services are connected together when using websockets, you also have to inject/extract the context on each end of the request. See https://datadog.github.io/dd-trace-js/interfaces/tracer.html#inject and https://datadog.github.io/dd-trace-js/interfaces/tracer.html#extract

**Comment by zhaoyi0113** [comment]
awesome, thanks for your quick response.
