### ISSUE TITLE
Service is not automatically populated

### ISSUE THREAD

**Issue by grahamlyons** [DataDog/dd-trace-js#850]
**Describe the bug**
In an Express app the `service` label was not automatically populated and traces were dropped by the agent. Lines like this appeared in the agent logs:
```
dropping trace reason: invalid span: empty `Service`...
```

I thought this was an issue with the documentation - DataDog/documentation#6517 - but was told to file it here.

How should the library get a default service name?

**Environment**
Express/pm2

* **Operating system:**
Ubuntu 18.04
* **Node version:**
0.12
* **Tracer version:**
* **Agent version:**
7

**Comment by rochdev** [comment]
Since we don't support Node 0.12, I assume you meant 12, but please correct me if that's wrong.

The tracer will attempt to get the service name from the name field in the `package.json` of the project if available, and will otherwise fallback to `node`. This behavior can be seen [here](https://github.com/DataDog/dd-trace-js/blob/5c449e2d3317db7d5ce7d4760b39c7eb7bfb03ad/packages/dd-trace/src/config.js#L65).

In theory, it shouldn't be possible that it's empty since there is a fallback to a hardcoded string, but it's possible if one of the options is an empty string that `coalesce` will use that instead of the fallback, which would result in an empty service name, which would be a bug.

Do you know if there is an empty string defined anywhere? For example the `DD_SERVICE_NAME` environment variable or an empty `name` field in `package.json`?

**Comment by grahamlyons** [comment]
Aha, gotcha. There's no `"name"` in `package.json`. Thank you!
