### ISSUE TITLE
GraphQL Tracing over WebSockets

### ISSUE THREAD

**Issue by jon-whit** [DataDog/dd-trace-js#975]
Does the `dd-trace-js` GraphQL plugin support tracing mutations and queries over WebSockets?

**Comment by rochdev** [comment]
It supports queries and mutations regardless of the transport used, so yes. One major difference however is that since we explicitly support HTTP but not websockets, there is usually a single root span for the entire trace from the `http` integration. When using websockets this will not be the case, so the top-level GraphQL operations will appear as different traces. All this really means is that the actual query/mutation will be its own trace, while the parsing and validation will appear as different traces. In most cases, this is fine if you only care about the query itself. Otherwise you would have to manually start a trace in the websocket handler to wrap the GraphQL spans.
